#!/bin/bash
# Generate a .env file for ms-utrustning.
#
# Usage:
#   ./gen-env.sh dev              # Local development (default)
#   ./gen-env.sh demo             # Demo deployment (registry images, CHANGEME placeholders)
#   ./gen-env.sh demo --local     # Demo on dev machine (local builds, localhost)
#   ./gen-env.sh prod             # Production deployment
#
# Flags:
#   --force   Required when switching modes. Same-mode reruns work without it.
#   --local   Use local image names and localhost origin (for testing on dev machine)
#
# Writes to .env in the current directory. On rerun, all user-edited values are
# preserved. Only AUTH_SECRET is always regenerated (security).

set -e

FORCE=false
LOCAL=false
for arg in "$@"; do
  [[ "$arg" == "--force" ]] && FORCE=true
  [[ "$arg" == "--local" ]] && LOCAL=true
done

# Read all existing key=value pairs before overwriting
declare -A OLD_VALUES
if [[ -f .env ]]; then
  while IFS='=' read -r key rest; do
    [[ "$key" =~ ^[[:space:]]*# || -z "$key" ]] && continue
    OLD_VALUES["$key"]="$rest"
  done < .env
fi

OLD_MODE="${OLD_VALUES[GEN_ENV_MODE]:-}"
OLD_PG_PASSWORD="${OLD_VALUES[POSTGRES_PASSWORD]:-}"

# Default to the existing mode so bare reruns always use the right mode.
# An explicit argument overrides this.
MODE="${1:-${OLD_MODE:-dev}}"

if [[ "$MODE" != "dev" && "$MODE" != "demo" && "$MODE" != "prod" ]]; then
  echo "Usage: $0 [dev|demo|prod] [--force] [--local]"
  exit 1
fi

# Switching modes requires --force as an explicit acknowledgment
if [[ -f .env && -n "$OLD_MODE" && "$OLD_MODE" != "$MODE" && "$FORCE" != true ]]; then
  echo "Existing .env was generated for '$OLD_MODE'. Switching to '$MODE' requires --force."
  exit 1
fi

random_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

random_password() {
  openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p
}

# Mode-specific defaults (used only when no old value exists to restore)
case "$MODE" in
  dev)
    DEV_MODE=true
    DEMO_MODE=false
    BUILD_TARGET=dev
    COMPOSE_FILE="docker-compose.yml:docker-compose.override.yml"
    AUTH_SECRET="dev-secret-not-for-production"
    AUTH_KEYCLOAK_SECRET=""
    POSTGRES_PASSWORD="utrustning"
    SETTINGS_ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)
    API_IMAGE="ms-utrustning-api"
    WEB_IMAGE="ms-utrustning-web"
    DEMO_URL="https://demo.scoutrustning.se"
    PROD_URL="https://scoutrustning.se"
    ;;
  demo)
    DEV_MODE=true
    DEMO_MODE=true
    BUILD_TARGET=production
    COMPOSE_FILE="docker-compose.yml"
    AUTH_SECRET=$(random_secret)
    AUTH_KEYCLOAK_SECRET="CHANGEME_keycloak-client-secret"
    POSTGRES_PASSWORD="${OLD_PG_PASSWORD:-$(random_password)}"
    SETTINGS_ENCRYPTION_KEY="${OLD_VALUES[SETTINGS_ENCRYPTION_KEY]:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)}"
    API_IMAGE="ghcr.io/malarscouterna/ms-utrustning-api:latest"
    WEB_IMAGE="ghcr.io/malarscouterna/ms-utrustning-web:latest"
    DEMO_URL=""
    PROD_URL="https://scoutrustning.se"
    ;;
  prod)
    DEV_MODE=false
    DEMO_MODE=false
    BUILD_TARGET=production
    COMPOSE_FILE="docker-compose.yml"
    AUTH_SECRET=$(random_secret)
    AUTH_KEYCLOAK_SECRET="CHANGEME_keycloak-client-secret"
    POSTGRES_PASSWORD="${OLD_PG_PASSWORD:-$(random_password)}"
    SETTINGS_ENCRYPTION_KEY="${OLD_VALUES[SETTINGS_ENCRYPTION_KEY]:-$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)}"
    API_IMAGE="ghcr.io/malarscouterna/ms-utrustning-api:latest"
    WEB_IMAGE="ghcr.io/malarscouterna/ms-utrustning-web:latest"
    DEMO_URL="https://demo.scoutrustning.se"
    PROD_URL=""
    ;;
esac

# --local: override for testing on dev machine
if [[ "$LOCAL" == true && "$MODE" != "dev" ]]; then
  POSTGRES_PASSWORD="utrustning"
  API_IMAGE="ms-utrustning-api"
  WEB_IMAGE="ms-utrustning-web"
fi

# Detect Postgres password change (before we might restore the old value)
PG_CHANGED=false
if [[ -n "$OLD_PG_PASSWORD" && "$OLD_PG_PASSWORD" != "$POSTGRES_PASSWORD" ]]; then
  PG_CHANGED=true
fi

cat > .env << EOF
# Generated by gen-env.sh for: $MODE$([ "$LOCAL" = true ] && echo " (local)")
# $(date -Iseconds)
#
# ┌──────────────┬───────────┬───────────┬────────────┐
# │              │ Dev       │ Demo      │ Production │
# ├──────────────┼───────────┼───────────┼────────────┤
# │ DEV_MODE     │ true      │ true      │ false      │
# │ DEMO_MODE    │ false     │ true      │ false      │
# │ BUILD_TARGET │ dev       │ production│ production │
# │ AUTH_SECRET  │ static    │ generated │ generated  │
# │ PG password  │ static    │ generated │ generated  │
# └──────────────┴───────────┴───────────┴────────────┘
GEN_ENV_MODE=$MODE

# ── Compose ───────────────────────────────────────────────
COMPOSE_FILE=$COMPOSE_FILE

# ── Mode ──────────────────────────────────────────────────
DEV_MODE=$DEV_MODE
DEMO_MODE=$DEMO_MODE
BUILD_TARGET=$BUILD_TARGET

# ── Database ──────────────────────────────────────────────
POSTGRES_USER=utrustning
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=utrustning

# ── Ports ─────────────────────────────────────────────────
API_PORT=8080
WEB_PORT=3000

# ── URLs ──────────────────────────────────────────────────
JWKS_URL=https://dev.id.scouterna.se/realms/scoutnet/protocol/openid-connect/certs
DEMO_URL=$DEMO_URL
PROD_URL=$PROD_URL

# ── Auth (OIDC via ScoutID/Keycloak) ─────────────────────
AUTH_SECRET=$AUTH_SECRET
AUTH_KEYCLOAK_ID=ms-utrustning
AUTH_KEYCLOAK_SECRET=$AUTH_KEYCLOAK_SECRET
AUTH_KEYCLOAK_ISSUER=https://dev.id.scouterna.se/realms/scoutnet

# ── Images ────────────────────────────────────────────────
API_IMAGE=$API_IMAGE
WEB_IMAGE=$WEB_IMAGE
EOF

if [[ "$MODE" == "dev" ]]; then
  cat >> .env << EOF

# ── Encryption ────────────────────────────────────────────
# Auto-generated for dev. Safe to regenerate (no encrypted data persists).
SETTINGS_ENCRYPTION_KEY=$SETTINGS_ENCRYPTION_KEY

# ── System-wide SMTP ──────────────────────────────────────
# Optional in dev — leave blank to skip email sending entirely.
# Fill in real SMTP credentials to test against a live provider, or use a
# local catch-all like Mailpit (see README § Testing emails in dev).
SMTP_DEFAULT_FROM=dev@localhost
SMTP_DEFAULT_HOST=mailpit
SMTP_DEFAULT_PORT=1025
SMTP_DEFAULT_TLS=starttls
SMTP_DEFAULT_USER=
SMTP_DEFAULT_KEY=
APP_BASE_URL=http://localhost:5173

# ── Dev GChat testing (optional) ──────────────────────────
# Fill in to test GChat notifications locally. Place the service account JSON
# at the path below, then re-run dev-seed.sh to connect and link teams.
# Leave blank to skip GChat setup.
DEV_GCHAT_KEY_PATH=
DEV_GCHAT_SPACE_ID=
DEV_GCHAT_ADMIN_EMAIL=
EOF
else
  cat >> .env << EOF

# ── Encryption ────────────────────────────────────────────
# 64-char hex key (256 bits). Auto-generated — do not lose.
SETTINGS_ENCRYPTION_KEY=$SETTINGS_ENCRYPTION_KEY

# ── System-wide SMTP (fallback when group has no own config) ──
# Used for all notification emails. Per-group SMTP can override this.
SMTP_DEFAULT_FROM=CHANGEME_noreply@example.com
SMTP_DEFAULT_HOST=CHANGEME_smtp.example.com
SMTP_DEFAULT_PORT=587
SMTP_DEFAULT_TLS=starttls
SMTP_DEFAULT_USER=CHANGEME_apikey
SMTP_DEFAULT_KEY=CHANGEME_your-smtp-api-key
APP_BASE_URL=CHANGEME_https://utrustning.yourscoutgroup.se
EOF
fi

# Restore user-edited values from the old .env by patching the generated file.
# Every non-empty, non-CHANGEME_ value is preserved. AUTH_SECRET is always
# regenerated for security. --local skips POSTGRES_PASSWORD since it was
# intentionally forced to a localhost value above.
NEVER_RESTORE="AUTH_SECRET GEN_ENV_MODE"
LOCAL_SKIP="POSTGRES_PASSWORD"

for key in "${!OLD_VALUES[@]}"; do
  old_val="${OLD_VALUES[$key]}"
  [[ -z "$old_val" || "$old_val" == CHANGEME_* ]] && continue
  [[ " $NEVER_RESTORE " == *" $key "* ]] && continue
  [[ "$LOCAL" == true && " $LOCAL_SKIP " == *" $key "* ]] && continue
  # Never restore DEV_* vars into a non-dev .env
  [[ "$MODE" != "dev" && "$key" == DEV_* ]] && continue
  grep -qE "^${key}=" .env || continue
  sed -i "s|^${key}=.*|${key}=${old_val}|" .env
done

echo "Generated .env for: $MODE$([ "$LOCAL" = true ] && echo " (local)")"

if [[ "$PG_CHANGED" == true ]]; then
  echo ""
  echo "⚠  Postgres password changed. The existing database volume still has the old password."
  echo "   To reset: docker compose down -v && docker compose up -d"
  echo "   Then re-seed: ./dev-seed.sh"
fi

if grep -q "CHANGEME" .env; then
  echo ""
  echo "⚠  You have values to fill in:"
  grep "CHANGEME" .env | sed 's/^/   /'
  echo ""
  echo "Replace CHANGEME_... with real values before starting."
fi

