#!/bin/bash
# Generate a .env file for ms-utrustning.
#
# Usage:
#   ./gen-env.sh dev              # Local development (default)
#   ./gen-env.sh demo             # Demo deployment (registry images, CHANGEME placeholders)
#   ./gen-env.sh demo --local     # Demo on dev machine (local builds, localhost)
#   ./gen-env.sh prod             # Production deployment
#
# Flags:
#   --force   Overwrite existing .env (preserves user-edited values)
#   --local   Use local image names and localhost origin (for testing on dev machine)
#
# Writes to .env in the current directory.

set -e

MODE="${1:-dev}"
FORCE=false
LOCAL=false
for arg in "$@"; do
  [[ "$arg" == "--force" ]] && FORCE=true
  [[ "$arg" == "--local" ]] && LOCAL=true
done

if [[ "$MODE" != "dev" && "$MODE" != "demo" && "$MODE" != "prod" ]]; then
  echo "Usage: $0 [dev|demo|prod] [--force] [--local]"
  exit 1
fi

# Read values from existing .env before overwriting
OLD_ORIGIN=""
OLD_KEYCLOAK_SECRET=""
OLD_PG_PASSWORD=""
if [[ -f .env ]]; then
  OLD_ORIGIN=$(grep -E '^ORIGIN=' .env | cut -d= -f2- || true)
  OLD_KEYCLOAK_SECRET=$(grep -E '^AUTH_KEYCLOAK_SECRET=' .env | cut -d= -f2- || true)
  OLD_PG_PASSWORD=$(grep -E '^POSTGRES_PASSWORD=' .env | cut -d= -f2- || true)
fi

if [[ -f .env && "$FORCE" != true ]]; then
  echo ".env already exists. Use --force to overwrite."
  exit 1
fi

random_secret() {
  openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

random_password() {
  openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p
}

# Mode-specific defaults
case "$MODE" in
  dev)
    DEV_MODE=true
    DEMO_MODE=false
    BUILD_TARGET=dev
    COMPOSE_FILE="docker-compose.yml:docker-compose.override.yml"
    AUTH_SECRET="dev-secret-not-for-production"
    ORIGIN="http://localhost:3000"
    AUTH_KEYCLOAK_SECRET=""
    POSTGRES_PASSWORD="utrustning"
    API_IMAGE="ms-utrustning-api"
    WEB_IMAGE="ms-utrustning-web"
    ;;
  demo)
    DEV_MODE=true
    DEMO_MODE=true
    BUILD_TARGET=production
    COMPOSE_FILE="docker-compose.yml"
    AUTH_SECRET=$(random_secret)
    ORIGIN="CHANGEME_https://your-demo-domain.example.com"
    AUTH_KEYCLOAK_SECRET="CHANGEME_keycloak-client-secret"
    POSTGRES_PASSWORD=$(random_password)
    API_IMAGE="ghcr.io/malarscouterna/ms-utrustning-api:latest"
    WEB_IMAGE="ghcr.io/malarscouterna/ms-utrustning-web:latest"
    ;;
  prod)
    DEV_MODE=false
    DEMO_MODE=false
    BUILD_TARGET=production
    COMPOSE_FILE="docker-compose.yml"
    AUTH_SECRET=$(random_secret)
    ORIGIN="CHANGEME_https://your-domain.example.com"
    AUTH_KEYCLOAK_SECRET="CHANGEME_keycloak-client-secret"
    POSTGRES_PASSWORD=$(random_password)
    API_IMAGE="ghcr.io/malarscouterna/ms-utrustning-api:latest"
    WEB_IMAGE="ghcr.io/malarscouterna/ms-utrustning-web:latest"
    ;;
esac

# --local: override for testing on dev machine
if [[ "$LOCAL" == true && "$MODE" != "dev" ]]; then
  ORIGIN="http://localhost:3000"
  POSTGRES_PASSWORD="utrustning"
  API_IMAGE="ms-utrustning-api"
  WEB_IMAGE="ms-utrustning-web"
fi

# Preserve user-edited values from old .env
if [[ -n "$OLD_ORIGIN" && "$OLD_ORIGIN" != CHANGEME_* && "$LOCAL" != true ]]; then
  ORIGIN="$OLD_ORIGIN"
fi
if [[ -n "$OLD_KEYCLOAK_SECRET" && "$OLD_KEYCLOAK_SECRET" != CHANGEME_* ]]; then
  AUTH_KEYCLOAK_SECRET="$OLD_KEYCLOAK_SECRET"
fi

# Detect Postgres password change
PG_CHANGED=false
if [[ -n "$OLD_PG_PASSWORD" && "$OLD_PG_PASSWORD" != "$POSTGRES_PASSWORD" ]]; then
  PG_CHANGED=true
fi

cat > .env << EOF
# Generated by gen-env.sh for: $MODE$([ "$LOCAL" = true ] && echo " (local)")
# $(date -Iseconds)
#
# ┌──────────────┬───────────┬───────────┬────────────┐
# │              │ Dev       │ Demo      │ Production │
# ├──────────────┼───────────┼───────────┼────────────┤
# │ DEV_MODE     │ true      │ true      │ false      │
# │ DEMO_MODE    │ false     │ true      │ false      │
# │ BUILD_TARGET │ dev       │ production│ production │
# │ AUTH_SECRET  │ static    │ generated │ generated  │
# │ PG password  │ static    │ generated │ generated  │
# └──────────────┴───────────┴───────────┴────────────┘

# ── Compose ───────────────────────────────────────────────
COMPOSE_FILE=$COMPOSE_FILE

# ── Mode ──────────────────────────────────────────────────
DEV_MODE=$DEV_MODE
DEMO_MODE=$DEMO_MODE
BUILD_TARGET=$BUILD_TARGET

# ── Database ──────────────────────────────────────────────
POSTGRES_USER=utrustning
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=utrustning

# ── Ports ─────────────────────────────────────────────────
API_PORT=8080
WEB_PORT=3000

# ── URLs ──────────────────────────────────────────────────
ORIGIN=$ORIGIN
JWKS_URL=https://dev.id.scouterna.se/realms/scoutnet/protocol/openid-connect/certs

# ── Auth (OIDC via ScoutID/Keycloak) ─────────────────────
AUTH_SECRET=$AUTH_SECRET
AUTH_KEYCLOAK_ID=ms-utrustning
AUTH_KEYCLOAK_SECRET=$AUTH_KEYCLOAK_SECRET
AUTH_KEYCLOAK_ISSUER=https://dev.id.scouterna.se/realms/scoutnet

# ── Images ────────────────────────────────────────────────
API_IMAGE=$API_IMAGE
WEB_IMAGE=$WEB_IMAGE
EOF

echo "Generated .env for: $MODE$([ "$LOCAL" = true ] && echo " (local)")"

if [[ "$PG_CHANGED" == true ]]; then
  echo ""
  echo "⚠  Postgres password changed. The existing database volume still has the old password."
  echo "   To reset: docker compose down -v && docker compose up -d"
  echo "   Then re-seed: ./dev-seed.sh"
fi

if grep -q "CHANGEME" .env; then
  echo ""
  echo "⚠  You have values to fill in:"
  grep "CHANGEME" .env | sed 's/^/   /'
  echo ""
  echo "Replace CHANGEME_... with real values before starting."
fi

if [[ "$ORIGIN" == http://* && "$ORIGIN" != "http://localhost"* ]]; then
  echo ""
  echo "⚠  ORIGIN uses http:// — OIDC requires https:// in demo/production."
  echo "   Current: $ORIGIN"
fi
