// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticlesByCategory = `-- name: CountArticlesByCategory :many
SELECT c.id, c.name, COUNT(a.id) AS count
FROM categories c
LEFT JOIN articles a ON a.category_id = c.id AND a.group_id = c.group_id
WHERE c.group_id = $1
GROUP BY c.id, c.name
ORDER BY c.sort_order
`

type CountArticlesByCategoryRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Count int64       `json:"count"`
}

func (q *Queries) CountArticlesByCategory(ctx context.Context, groupID string) ([]CountArticlesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countArticlesByCategory, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArticlesByCategoryRow{}
	for rows.Next() {
		var i CountArticlesByCategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countArticlesByLocation = `-- name: CountArticlesByLocation :many
SELECT l.id, l.name, COUNT(a.id) AS count
FROM locations l
LEFT JOIN articles a ON a.location_id = l.id AND a.group_id = l.group_id
WHERE l.group_id = $1
GROUP BY l.id, l.name
ORDER BY l.sort_order
`

type CountArticlesByLocationRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Count int64       `json:"count"`
}

func (q *Queries) CountArticlesByLocation(ctx context.Context, groupID string) ([]CountArticlesByLocationRow, error) {
	rows, err := q.db.Query(ctx, countArticlesByLocation, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArticlesByLocationRow{}
	for rows.Next() {
		var i CountArticlesByLocationRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    group_id, commercial_name, common_name, category_id, location_id,
    status, individually_tracked, requires_approval,
    description, instructions, purchase_date, purchase_price, place
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, requires_approval, image_path, description, instructions, purchase_date, purchase_price, place, drying_until, created_at, updated_at
`

type CreateArticleParams struct {
	GroupID             string         `json:"group_id"`
	CommercialName      string         `json:"commercial_name"`
	CommonName          string         `json:"common_name"`
	CategoryID          pgtype.UUID    `json:"category_id"`
	LocationID          pgtype.UUID    `json:"location_id"`
	Status              string         `json:"status"`
	IndividuallyTracked bool           `json:"individually_tracked"`
	RequiresApproval    bool           `json:"requires_approval"`
	Description         string         `json:"description"`
	Instructions        string         `json:"instructions"`
	PurchaseDate        pgtype.Date    `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric `json:"purchase_price"`
	Place               string         `json:"place"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.GroupID,
		arg.CommercialName,
		arg.CommonName,
		arg.CategoryID,
		arg.LocationID,
		arg.Status,
		arg.IndividuallyTracked,
		arg.RequiresApproval,
		arg.Description,
		arg.Instructions,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Place,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.RequiresApproval,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.DryingUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1 AND group_id = $2
`

type DeleteArticleParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) error {
	_, err := q.db.Exec(ctx, deleteArticle, arg.ID, arg.GroupID)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.requires_approval, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.drying_until, a.created_at, a.updated_at,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.id = $1 AND a.group_id = $2
`

type GetArticleParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetArticleRow struct {
	ID                  pgtype.UUID        `json:"id"`
	GroupID             string             `json:"group_id"`
	CommercialName      string             `json:"commercial_name"`
	CommonName          string             `json:"common_name"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	Status              string             `json:"status"`
	IndividuallyTracked bool               `json:"individually_tracked"`
	RequiresApproval    bool               `json:"requires_approval"`
	ImagePath           pgtype.Text        `json:"image_path"`
	Description         string             `json:"description"`
	Instructions        string             `json:"instructions"`
	PurchaseDate        pgtype.Date        `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric     `json:"purchase_price"`
	Place               string             `json:"place"`
	DryingUntil         pgtype.Date        `json:"drying_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LocationName        string             `json:"location_name"`
	CategoryName        string             `json:"category_name"`
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (GetArticleRow, error) {
	row := q.db.QueryRow(ctx, getArticle, arg.ID, arg.GroupID)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.RequiresApproval,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.DryingUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationName,
		&i.CategoryName,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.requires_approval, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.drying_until, a.created_at, a.updated_at,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND ($2::uuid IS NULL OR a.category_id = $2)
    AND ($3::uuid IS NULL OR a.location_id = $3)
    AND (COALESCE(array_length($4::text[], 1), 0) = 0 OR a.status = ANY($4))
    AND ($5::text IS NULL OR a.common_name ILIKE '%' || $5 || '%' OR a.commercial_name ILIKE '%' || $5 || '%')
ORDER BY c.sort_order, c.name, a.commercial_name, a.common_name
`

type ListArticlesParams struct {
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	LocationID pgtype.UUID `json:"location_id"`
	Statuses   []string    `json:"statuses"`
	Search     pgtype.Text `json:"search"`
}

type ListArticlesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	GroupID             string             `json:"group_id"`
	CommercialName      string             `json:"commercial_name"`
	CommonName          string             `json:"common_name"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	Status              string             `json:"status"`
	IndividuallyTracked bool               `json:"individually_tracked"`
	RequiresApproval    bool               `json:"requires_approval"`
	ImagePath           pgtype.Text        `json:"image_path"`
	Description         string             `json:"description"`
	Instructions        string             `json:"instructions"`
	PurchaseDate        pgtype.Date        `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric     `json:"purchase_price"`
	Place               string             `json:"place"`
	DryingUntil         pgtype.Date        `json:"drying_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LocationName        string             `json:"location_name"`
	CategoryName        string             `json:"category_name"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.GroupID,
		arg.CategoryID,
		arg.LocationID,
		arg.Statuses,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.Status,
			&i.IndividuallyTracked,
			&i.RequiresApproval,
			&i.ImagePath,
			&i.Description,
			&i.Instructions,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.Place,
			&i.DryingUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByUserBookings = `-- name: ListArticlesByUserBookings :many
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.requires_approval, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.drying_until, a.created_at, a.updated_at,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND (COALESCE(array_length($2::text[], 1), 0) = 0 OR a.status = ANY($2))
    AND (
        a.id IN (
            SELECT bi.article_id FROM booking_items bi
            JOIN bookings b ON bi.booking_id = b.id
            WHERE b.group_id = $1
                AND (b.created_by = $3 OR b.used_by_unit_id = ANY(
                    SELECT un.id FROM units un WHERE un.group_id = $1 AND un.name = ANY($4::text[])
                ))
        )
        OR a.id IN (
            SELECT ae.article_id FROM article_events ae
            WHERE ae.group_id = $1 AND ae.actor_id = $3
        )
    )
ORDER BY c.sort_order, c.name, a.commercial_name, a.common_name
`

type ListArticlesByUserBookingsParams struct {
	GroupID   string   `json:"group_id"`
	Statuses  []string `json:"statuses"`
	UserID    string   `json:"user_id"`
	UnitNames []string `json:"unit_names"`
}

type ListArticlesByUserBookingsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	GroupID             string             `json:"group_id"`
	CommercialName      string             `json:"commercial_name"`
	CommonName          string             `json:"common_name"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	LocationID          pgtype.UUID        `json:"location_id"`
	Status              string             `json:"status"`
	IndividuallyTracked bool               `json:"individually_tracked"`
	RequiresApproval    bool               `json:"requires_approval"`
	ImagePath           pgtype.Text        `json:"image_path"`
	Description         string             `json:"description"`
	Instructions        string             `json:"instructions"`
	PurchaseDate        pgtype.Date        `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric     `json:"purchase_price"`
	Place               string             `json:"place"`
	DryingUntil         pgtype.Date        `json:"drying_until"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LocationName        string             `json:"location_name"`
	CategoryName        string             `json:"category_name"`
}

// Returns articles with given statuses that are linked to the user's bookings
// (created by user or assigned to one of their units), or where the user
// reported an issue (is an actor on an article event).
func (q *Queries) ListArticlesByUserBookings(ctx context.Context, arg ListArticlesByUserBookingsParams) ([]ListArticlesByUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByUserBookings,
		arg.GroupID,
		arg.Statuses,
		arg.UserID,
		arg.UnitNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByUserBookingsRow{}
	for rows.Next() {
		var i ListArticlesByUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.Status,
			&i.IndividuallyTracked,
			&i.RequiresApproval,
			&i.ImagePath,
			&i.Description,
			&i.Instructions,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.Place,
			&i.DryingUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    commercial_name = $1,
    common_name = $2,
    category_id = $3,
    location_id = $4,
    status = $5,
    individually_tracked = $6,
    requires_approval = $7,
    description = $8,
    instructions = $9,
    purchase_date = $10,
    purchase_price = $11,
    place = $12,
    updated_at = now()
WHERE id = $13 AND group_id = $14
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, requires_approval, image_path, description, instructions, purchase_date, purchase_price, place, drying_until, created_at, updated_at
`

type UpdateArticleParams struct {
	CommercialName      string         `json:"commercial_name"`
	CommonName          string         `json:"common_name"`
	CategoryID          pgtype.UUID    `json:"category_id"`
	LocationID          pgtype.UUID    `json:"location_id"`
	Status              string         `json:"status"`
	IndividuallyTracked bool           `json:"individually_tracked"`
	RequiresApproval    bool           `json:"requires_approval"`
	Description         string         `json:"description"`
	Instructions        string         `json:"instructions"`
	PurchaseDate        pgtype.Date    `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric `json:"purchase_price"`
	Place               string         `json:"place"`
	ID                  pgtype.UUID    `json:"id"`
	GroupID             string         `json:"group_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.CommercialName,
		arg.CommonName,
		arg.CategoryID,
		arg.LocationID,
		arg.Status,
		arg.IndividuallyTracked,
		arg.RequiresApproval,
		arg.Description,
		arg.Instructions,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Place,
		arg.ID,
		arg.GroupID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.RequiresApproval,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.DryingUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArticleStatus = `-- name: UpdateArticleStatus :one
UPDATE articles SET status = $1, drying_until = $2, updated_at = now()
WHERE id = $3 AND group_id = $4
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, requires_approval, image_path, description, instructions, purchase_date, purchase_price, place, drying_until, created_at, updated_at
`

type UpdateArticleStatusParams struct {
	Status      string      `json:"status"`
	DryingUntil pgtype.Date `json:"drying_until"`
	ID          pgtype.UUID `json:"id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) UpdateArticleStatus(ctx context.Context, arg UpdateArticleStatusParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticleStatus,
		arg.Status,
		arg.DryingUntil,
		arg.ID,
		arg.GroupID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.RequiresApproval,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.DryingUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
