// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateArticleLocation = `-- name: BulkUpdateArticleLocation :execrows
UPDATE articles SET location_id = $1, updated_at = now()
WHERE id = ANY($2::uuid[]) AND group_id = $3
`

type BulkUpdateArticleLocationParams struct {
	LocationID pgtype.UUID   `json:"location_id"`
	Ids        []pgtype.UUID `json:"ids"`
	GroupID    string        `json:"group_id"`
}

func (q *Queries) BulkUpdateArticleLocation(ctx context.Context, arg BulkUpdateArticleLocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateArticleLocation, arg.LocationID, arg.Ids, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkUpdateArticleStatus = `-- name: BulkUpdateArticleStatus :execrows
UPDATE articles SET status = $1, updated_at = now()
WHERE id = ANY($2::uuid[]) AND group_id = $3
`

type BulkUpdateArticleStatusParams struct {
	Status  string        `json:"status"`
	Ids     []pgtype.UUID `json:"ids"`
	GroupID string        `json:"group_id"`
}

func (q *Queries) BulkUpdateArticleStatus(ctx context.Context, arg BulkUpdateArticleStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateArticleStatus, arg.Status, arg.Ids, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countArticlesByCategory = `-- name: CountArticlesByCategory :many
SELECT c.id, c.name, COUNT(a.id) AS count
FROM categories c
LEFT JOIN articles a ON a.category_id = c.id AND a.group_id = c.group_id
WHERE c.group_id = $1
GROUP BY c.id, c.name
ORDER BY c.sort_order
`

type CountArticlesByCategoryRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Count int64       `json:"count"`
}

func (q *Queries) CountArticlesByCategory(ctx context.Context, groupID string) ([]CountArticlesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countArticlesByCategory, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArticlesByCategoryRow{}
	for rows.Next() {
		var i CountArticlesByCategoryRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countArticlesByLocation = `-- name: CountArticlesByLocation :many
SELECT l.id, l.name, COUNT(a.id) AS count
FROM locations l
LEFT JOIN articles a ON a.location_id = l.id AND a.group_id = l.group_id
WHERE l.group_id = $1
GROUP BY l.id, l.name
ORDER BY l.sort_order
`

type CountArticlesByLocationRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Count int64       `json:"count"`
}

func (q *Queries) CountArticlesByLocation(ctx context.Context, groupID string) ([]CountArticlesByLocationRow, error) {
	rows, err := q.db.Query(ctx, countArticlesByLocation, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArticlesByLocationRow{}
	for rows.Next() {
		var i CountArticlesByLocationRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countArticlesInGroup = `-- name: CountArticlesInGroup :one
SELECT COUNT(*) AS count
FROM articles a
WHERE a.group_id = $1
    AND a.commercial_name = $2
    AND a.location_id = $3
    AND a.status != 'archived'
`

type CountArticlesInGroupParams struct {
	GroupID        string      `json:"group_id"`
	CommercialName string      `json:"commercial_name"`
	LocationID     pgtype.UUID `json:"location_id"`
}

// Counts non-archived articles in a quantity tracked group.
func (q *Queries) CountArticlesInGroup(ctx context.Context, arg CountArticlesInGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesInGroup, arg.GroupID, arg.CommercialName, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    group_id, commercial_name, common_name, category_id, location_id,
    status, individually_tracked, approval_level,
    description, instructions, purchase_date, purchase_price, place, manager_notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13, $14
)
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, image_path, description, instructions, purchase_date, purchase_price, place, created_at, updated_at, expected_available_date, approval_level, import_batch_id, manager_notes
`

type CreateArticleParams struct {
	GroupID             string         `json:"group_id"`
	CommercialName      string         `json:"commercial_name"`
	CommonName          string         `json:"common_name"`
	CategoryID          pgtype.UUID    `json:"category_id"`
	LocationID          pgtype.UUID    `json:"location_id"`
	Status              string         `json:"status"`
	IndividuallyTracked bool           `json:"individually_tracked"`
	ApprovalLevel       string         `json:"approval_level"`
	Description         string         `json:"description"`
	Instructions        string         `json:"instructions"`
	PurchaseDate        pgtype.Date    `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric `json:"purchase_price"`
	Place               string         `json:"place"`
	ManagerNotes        string         `json:"manager_notes"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.GroupID,
		arg.CommercialName,
		arg.CommonName,
		arg.CategoryID,
		arg.LocationID,
		arg.Status,
		arg.IndividuallyTracked,
		arg.ApprovalLevel,
		arg.Description,
		arg.Instructions,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Place,
		arg.ManagerNotes,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedAvailableDate,
		&i.ApprovalLevel,
		&i.ImportBatchID,
		&i.ManagerNotes,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1 AND group_id = $2
`

type DeleteArticleParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteArticle(ctx context.Context, arg DeleteArticleParams) error {
	_, err := q.db.Exec(ctx, deleteArticle, arg.ID, arg.GroupID)
	return err
}

const findReplacementArticle = `-- name: FindReplacementArticle :one
SELECT a.id
FROM articles a
WHERE a.group_id = $1
    AND a.commercial_name = $2
    AND a.location_id = $3
    AND a.status IN ('ok', 'reported_usable')
    AND a.id != ALL($4::uuid[])
    AND a.id NOT IN (
        SELECT bi.article_id FROM booking_items bi
        JOIN bookings b ON bi.booking_id = b.id
        WHERE b.group_id = $1
            AND b.status IN ('confirmed', 'approved', 'picked_up', 'submitted', 'draft')
            AND b.start_date <= $5
            AND b.end_date >= $6
            AND (bi.return_status IS NULL OR bi.return_status IN ('pending', 'delayed'))
    )
ORDER BY a.created_at
LIMIT 1
`

type FindReplacementArticleParams struct {
	GroupID        string        `json:"group_id"`
	CommercialName string        `json:"commercial_name"`
	LocationID     pgtype.UUID   `json:"location_id"`
	ExcludeIds     []pgtype.UUID `json:"exclude_ids"`
	EndDate        pgtype.Date   `json:"end_date"`
	StartDate      pgtype.Date   `json:"start_date"`
}

// Finds a replacement article with the same commercial_name + location, bookable status,
// not in the given exclude list, and not in any overlapping active booking.
func (q *Queries) FindReplacementArticle(ctx context.Context, arg FindReplacementArticleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findReplacementArticle,
		arg.GroupID,
		arg.CommercialName,
		arg.LocationID,
		arg.ExcludeIds,
		arg.EndDate,
		arg.StartDate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getArticle = `-- name: GetArticle :one
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.created_at, a.updated_at, a.expected_available_date, a.approval_level, a.import_batch_id, a.manager_notes,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.id = $1 AND a.group_id = $2
`

type GetArticleParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetArticleRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	ImagePath             pgtype.Text        `json:"image_path"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel         string             `json:"approval_level"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes          string             `json:"manager_notes"`
	LocationName          string             `json:"location_name"`
	CategoryName          string             `json:"category_name"`
}

func (q *Queries) GetArticle(ctx context.Context, arg GetArticleParams) (GetArticleRow, error) {
	row := q.db.QueryRow(ctx, getArticle, arg.ID, arg.GroupID)
	var i GetArticleRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedAvailableDate,
		&i.ApprovalLevel,
		&i.ImportBatchID,
		&i.ManagerNotes,
		&i.LocationName,
		&i.CategoryName,
	)
	return i, err
}

const getArticleGroupInfo = `-- name: GetArticleGroupInfo :one
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.created_at, a.updated_at, a.expected_available_date, a.approval_level, a.import_batch_id, a.manager_notes,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND a.commercial_name = $2
    AND a.location_id = $3
ORDER BY a.created_at
LIMIT 1
`

type GetArticleGroupInfoParams struct {
	GroupID        string      `json:"group_id"`
	CommercialName string      `json:"commercial_name"`
	LocationID     pgtype.UUID `json:"location_id"`
}

type GetArticleGroupInfoRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	ImagePath             pgtype.Text        `json:"image_path"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel         string             `json:"approval_level"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes          string             `json:"manager_notes"`
	LocationName          string             `json:"location_name"`
	CategoryName          string             `json:"category_name"`
}

// Returns shared fields from the representative (oldest) article in a group.
func (q *Queries) GetArticleGroupInfo(ctx context.Context, arg GetArticleGroupInfoParams) (GetArticleGroupInfoRow, error) {
	row := q.db.QueryRow(ctx, getArticleGroupInfo, arg.GroupID, arg.CommercialName, arg.LocationID)
	var i GetArticleGroupInfoRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedAvailableDate,
		&i.ApprovalLevel,
		&i.ImportBatchID,
		&i.ManagerNotes,
		&i.LocationName,
		&i.CategoryName,
	)
	return i, err
}

const listActiveBookingConflicts = `-- name: ListActiveBookingConflicts :many
SELECT DISTINCT a.id AS article_id, a.common_name AS article_name,
    b.id AS booking_id,
    b.start_date AS booking_start_date, b.end_date AS booking_end_date,
    COALESCE(u.name, b.used_by_external, '') AS booking_unit
FROM articles a
JOIN booking_items bi ON bi.article_id = a.id
JOIN bookings b ON bi.booking_id = b.id
LEFT JOIN units u ON b.used_by_unit_id = u.id
WHERE a.id = ANY($1::uuid[]) AND a.group_id = $2
    AND b.status IN ('confirmed', 'approved', 'picked_up')
    AND (bi.return_status IS NULL OR bi.return_status IN ('pending', 'delayed'))
`

type ListActiveBookingConflictsParams struct {
	Ids     []pgtype.UUID `json:"ids"`
	GroupID string        `json:"group_id"`
}

type ListActiveBookingConflictsRow struct {
	ArticleID        pgtype.UUID `json:"article_id"`
	ArticleName      string      `json:"article_name"`
	BookingID        pgtype.UUID `json:"booking_id"`
	BookingStartDate pgtype.Date `json:"booking_start_date"`
	BookingEndDate   pgtype.Date `json:"booking_end_date"`
	BookingUnit      string      `json:"booking_unit"`
}

// Returns articles from the given list that are in active bookings (confirmed/approved/picked_up)
// with booking details for conflict resolution.
func (q *Queries) ListActiveBookingConflicts(ctx context.Context, arg ListActiveBookingConflictsParams) ([]ListActiveBookingConflictsRow, error) {
	rows, err := q.db.Query(ctx, listActiveBookingConflicts, arg.Ids, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBookingConflictsRow{}
	for rows.Next() {
		var i ListActiveBookingConflictsRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.ArticleName,
			&i.BookingID,
			&i.BookingStartDate,
			&i.BookingEndDate,
			&i.BookingUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.created_at, a.updated_at, a.expected_available_date, a.approval_level, a.import_batch_id, a.manager_notes,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND ($2::uuid IS NULL OR a.category_id = $2)
    AND ($3::uuid IS NULL OR a.location_id = $3)
    AND (COALESCE(array_length($4::text[], 1), 0) = 0 OR a.status = ANY($4))
    AND ($5::text IS NULL OR a.common_name ILIKE '%' || $5 || '%' OR a.commercial_name ILIKE '%' || $5 || '%')
ORDER BY c.sort_order, c.name, a.commercial_name, a.common_name
`

type ListArticlesParams struct {
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	LocationID pgtype.UUID `json:"location_id"`
	Statuses   []string    `json:"statuses"`
	Search     pgtype.Text `json:"search"`
}

type ListArticlesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	ImagePath             pgtype.Text        `json:"image_path"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel         string             `json:"approval_level"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes          string             `json:"manager_notes"`
	LocationName          string             `json:"location_name"`
	CategoryName          string             `json:"category_name"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.GroupID,
		arg.CategoryID,
		arg.LocationID,
		arg.Statuses,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.Status,
			&i.IndividuallyTracked,
			&i.ImagePath,
			&i.Description,
			&i.Instructions,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.Place,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectedAvailableDate,
			&i.ApprovalLevel,
			&i.ImportBatchID,
			&i.ManagerNotes,
			&i.LocationName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByUserBookings = `-- name: ListArticlesByUserBookings :many
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.created_at, a.updated_at, a.expected_available_date, a.approval_level, a.import_batch_id, a.manager_notes,
    l.name AS location_name,
    c.name AS category_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND (COALESCE(array_length($2::text[], 1), 0) = 0 OR a.status = ANY($2))
    AND (
        a.id IN (
            SELECT bi.article_id FROM booking_items bi
            JOIN bookings b ON bi.booking_id = b.id
            WHERE b.group_id = $1
                AND (b.created_by = $3 OR b.used_by_unit_id = ANY(
                    SELECT un.id FROM units un WHERE un.group_id = $1 AND un.name = ANY($4::text[])
                ))
        )
        OR a.id IN (
            SELECT ae.article_id FROM article_events ae
            WHERE ae.group_id = $1 AND ae.actor_id = $3
        )
    )
ORDER BY c.sort_order, c.name, a.commercial_name, a.common_name
`

type ListArticlesByUserBookingsParams struct {
	GroupID   string   `json:"group_id"`
	Statuses  []string `json:"statuses"`
	UserID    string   `json:"user_id"`
	UnitNames []string `json:"unit_names"`
}

type ListArticlesByUserBookingsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	ImagePath             pgtype.Text        `json:"image_path"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel         string             `json:"approval_level"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes          string             `json:"manager_notes"`
	LocationName          string             `json:"location_name"`
	CategoryName          string             `json:"category_name"`
}

// Returns articles with given statuses that are linked to the user's bookings
// (created by user or assigned to one of their units), or where the user
// reported an issue (is an actor on an article event).
func (q *Queries) ListArticlesByUserBookings(ctx context.Context, arg ListArticlesByUserBookingsParams) ([]ListArticlesByUserBookingsRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByUserBookings,
		arg.GroupID,
		arg.Statuses,
		arg.UserID,
		arg.UnitNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByUserBookingsRow{}
	for rows.Next() {
		var i ListArticlesByUserBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.Status,
			&i.IndividuallyTracked,
			&i.ImagePath,
			&i.Description,
			&i.Instructions,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.Place,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectedAvailableDate,
			&i.ApprovalLevel,
			&i.ImportBatchID,
			&i.ManagerNotes,
			&i.LocationName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesWithAvailability = `-- name: ListArticlesWithAvailability :many
SELECT a.id, a.group_id, a.commercial_name, a.common_name, a.category_id, a.location_id, a.status, a.individually_tracked, a.image_path, a.description, a.instructions, a.purchase_date, a.purchase_price, a.place, a.created_at, a.updated_at, a.expected_available_date, a.approval_level, a.import_batch_id, a.manager_notes,
    l.name AS location_name,
    c.name AS category_name,
    cur_booking.id AS current_booking_id,
    COALESCE(cur_booking.status, '') AS current_booking_status,
    cur_booking.end_date AS current_booking_end_date,
    cur_unit.name AS current_booking_unit_name
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
LEFT JOIN LATERAL (
    SELECT b.id, b.status, b.end_date, b.used_by_unit_id
    FROM booking_items bi
    JOIN bookings b ON bi.booking_id = b.id
    WHERE bi.article_id = a.id
        AND b.group_id = a.group_id
        AND b.status IN ('confirmed', 'approved', 'picked_up')
        AND b.start_date <= $1
        AND b.end_date >= $1
        AND (bi.return_status IS NULL OR bi.return_status IN ('pending', 'delayed'))
    ORDER BY b.start_date
    LIMIT 1
) cur_booking ON true
LEFT JOIN units cur_unit ON cur_booking.used_by_unit_id = cur_unit.id
WHERE a.group_id = $2
    AND ($3::uuid IS NULL OR a.category_id = $3)
    AND ($4::uuid IS NULL OR a.location_id = $4)
    AND (COALESCE(array_length($5::text[], 1), 0) = 0 OR a.status = ANY($5))
    AND ($6::text IS NULL OR a.common_name ILIKE '%' || $6 || '%' OR a.commercial_name ILIKE '%' || $6 || '%')
ORDER BY c.sort_order, c.name, a.commercial_name, a.common_name
`

type ListArticlesWithAvailabilityParams struct {
	AsOfDate   pgtype.Date `json:"as_of_date"`
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	LocationID pgtype.UUID `json:"location_id"`
	Statuses   []string    `json:"statuses"`
	Search     pgtype.Text `json:"search"`
}

type ListArticlesWithAvailabilityRow struct {
	ID                     pgtype.UUID        `json:"id"`
	GroupID                string             `json:"group_id"`
	CommercialName         string             `json:"commercial_name"`
	CommonName             string             `json:"common_name"`
	CategoryID             pgtype.UUID        `json:"category_id"`
	LocationID             pgtype.UUID        `json:"location_id"`
	Status                 string             `json:"status"`
	IndividuallyTracked    bool               `json:"individually_tracked"`
	ImagePath              pgtype.Text        `json:"image_path"`
	Description            string             `json:"description"`
	Instructions           string             `json:"instructions"`
	PurchaseDate           pgtype.Date        `json:"purchase_date"`
	PurchasePrice          pgtype.Numeric     `json:"purchase_price"`
	Place                  string             `json:"place"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate  pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel          string             `json:"approval_level"`
	ImportBatchID          pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes           string             `json:"manager_notes"`
	LocationName           string             `json:"location_name"`
	CategoryName           string             `json:"category_name"`
	CurrentBookingID       pgtype.UUID        `json:"current_booking_id"`
	CurrentBookingStatus   string             `json:"current_booking_status"`
	CurrentBookingEndDate  pgtype.Date        `json:"current_booking_end_date"`
	CurrentBookingUnitName pgtype.Text        `json:"current_booking_unit_name"`
}

// Returns articles enriched with current booking context for a given date.
func (q *Queries) ListArticlesWithAvailability(ctx context.Context, arg ListArticlesWithAvailabilityParams) ([]ListArticlesWithAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listArticlesWithAvailability,
		arg.AsOfDate,
		arg.GroupID,
		arg.CategoryID,
		arg.LocationID,
		arg.Statuses,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesWithAvailabilityRow{}
	for rows.Next() {
		var i ListArticlesWithAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.Status,
			&i.IndividuallyTracked,
			&i.ImagePath,
			&i.Description,
			&i.Instructions,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.Place,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpectedAvailableDate,
			&i.ApprovalLevel,
			&i.ImportBatchID,
			&i.ManagerNotes,
			&i.LocationName,
			&i.CategoryName,
			&i.CurrentBookingID,
			&i.CurrentBookingStatus,
			&i.CurrentBookingEndDate,
			&i.CurrentBookingUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestInGroup = `-- name: ListNewestInGroup :many
SELECT a.id
FROM articles a
WHERE a.group_id = $1
    AND a.commercial_name = $2
    AND a.location_id = $3
    AND a.status != 'archived'
    AND a.id NOT IN (
        SELECT bi.article_id FROM booking_items bi
        JOIN bookings b ON bi.booking_id = b.id
        WHERE b.group_id = $1
            AND b.status IN ('confirmed', 'approved', 'picked_up', 'submitted', 'draft')
            AND (bi.return_status IS NULL OR bi.return_status IN ('pending', 'delayed'))
    )
ORDER BY a.created_at DESC
`

type ListNewestInGroupParams struct {
	GroupID        string      `json:"group_id"`
	CommercialName string      `json:"commercial_name"`
	LocationID     pgtype.UUID `json:"location_id"`
}

// Returns articles in a group ordered newest first, for archiving excess.
// Excludes articles in active bookings.
func (q *Queries) ListNewestInGroup(ctx context.Context, arg ListNewestInGroupParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNewestInGroup, arg.GroupID, arg.CommercialName, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const propagateSharedFields = `-- name: PropagateSharedFields :execrows
UPDATE articles SET
    description = $1,
    instructions = $2,
    manager_notes = $3,
    category_id = $4,
    updated_at = now()
WHERE group_id = $5
    AND commercial_name = $6
    AND id != $7
`

type PropagateSharedFieldsParams struct {
	Description    string      `json:"description"`
	Instructions   string      `json:"instructions"`
	ManagerNotes   string      `json:"manager_notes"`
	CategoryID     pgtype.UUID `json:"category_id"`
	GroupID        string      `json:"group_id"`
	CommercialName string      `json:"commercial_name"`
	ExcludeID      pgtype.UUID `json:"exclude_id"`
}

// After editing an individually tracked article, sync shared fields to siblings.
func (q *Queries) PropagateSharedFields(ctx context.Context, arg PropagateSharedFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, propagateSharedFields,
		arg.Description,
		arg.Instructions,
		arg.ManagerNotes,
		arg.CategoryID,
		arg.GroupID,
		arg.CommercialName,
		arg.ExcludeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const swapBookingItemArticleByArticle = `-- name: SwapBookingItemArticleByArticle :execrows
UPDATE booking_items SET article_id = $1
WHERE article_id = $2 AND booking_id = $3 AND group_id = $4
`

type SwapBookingItemArticleByArticleParams struct {
	NewArticleID pgtype.UUID `json:"new_article_id"`
	OldArticleID pgtype.UUID `json:"old_article_id"`
	BookingID    pgtype.UUID `json:"booking_id"`
	GroupID      string      `json:"group_id"`
}

// Swap all booking_items referencing old_article_id in a specific booking to new_article_id.
func (q *Queries) SwapBookingItemArticleByArticle(ctx context.Context, arg SwapBookingItemArticleByArticleParams) (int64, error) {
	result, err := q.db.Exec(ctx, swapBookingItemArticleByArticle,
		arg.NewArticleID,
		arg.OldArticleID,
		arg.BookingID,
		arg.GroupID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    commercial_name = $1,
    common_name = $2,
    category_id = $3,
    location_id = $4,
    status = $5,
    individually_tracked = $6,
    approval_level = $7,
    description = $8,
    instructions = $9,
    purchase_date = $10,
    purchase_price = $11,
    place = $12,
    manager_notes = $13,
    updated_at = now()
WHERE id = $14 AND group_id = $15
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, image_path, description, instructions, purchase_date, purchase_price, place, created_at, updated_at, expected_available_date, approval_level, import_batch_id, manager_notes
`

type UpdateArticleParams struct {
	CommercialName      string         `json:"commercial_name"`
	CommonName          string         `json:"common_name"`
	CategoryID          pgtype.UUID    `json:"category_id"`
	LocationID          pgtype.UUID    `json:"location_id"`
	Status              string         `json:"status"`
	IndividuallyTracked bool           `json:"individually_tracked"`
	ApprovalLevel       string         `json:"approval_level"`
	Description         string         `json:"description"`
	Instructions        string         `json:"instructions"`
	PurchaseDate        pgtype.Date    `json:"purchase_date"`
	PurchasePrice       pgtype.Numeric `json:"purchase_price"`
	Place               string         `json:"place"`
	ManagerNotes        string         `json:"manager_notes"`
	ID                  pgtype.UUID    `json:"id"`
	GroupID             string         `json:"group_id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.CommercialName,
		arg.CommonName,
		arg.CategoryID,
		arg.LocationID,
		arg.Status,
		arg.IndividuallyTracked,
		arg.ApprovalLevel,
		arg.Description,
		arg.Instructions,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.Place,
		arg.ManagerNotes,
		arg.ID,
		arg.GroupID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedAvailableDate,
		&i.ApprovalLevel,
		&i.ImportBatchID,
		&i.ManagerNotes,
	)
	return i, err
}

const updateArticleGroupFields = `-- name: UpdateArticleGroupFields :execrows
UPDATE articles SET
    commercial_name = $1,
    common_name = $2,
    category_id = $3,
    location_id = $4,
    approval_level = $5,
    description = $6,
    instructions = $7,
    place = $8,
    manager_notes = $9,
    individually_tracked = $10,
    updated_at = now()
WHERE group_id = $11
    AND commercial_name = $12
    AND location_id = $13
`

type UpdateArticleGroupFieldsParams struct {
	NewCommercialName   string      `json:"new_commercial_name"`
	NewCommonName       string      `json:"new_common_name"`
	CategoryID          pgtype.UUID `json:"category_id"`
	NewLocationID       pgtype.UUID `json:"new_location_id"`
	ApprovalLevel       string      `json:"approval_level"`
	Description         string      `json:"description"`
	Instructions        string      `json:"instructions"`
	Place               string      `json:"place"`
	ManagerNotes        string      `json:"manager_notes"`
	IndividuallyTracked bool        `json:"individually_tracked"`
	GroupID             string      `json:"group_id"`
	OldCommercialName   string      `json:"old_commercial_name"`
	OldLocationID       pgtype.UUID `json:"old_location_id"`
}

// Updates shared fields for all articles in a quantity tracked group.
func (q *Queries) UpdateArticleGroupFields(ctx context.Context, arg UpdateArticleGroupFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateArticleGroupFields,
		arg.NewCommercialName,
		arg.NewCommonName,
		arg.CategoryID,
		arg.NewLocationID,
		arg.ApprovalLevel,
		arg.Description,
		arg.Instructions,
		arg.Place,
		arg.ManagerNotes,
		arg.IndividuallyTracked,
		arg.GroupID,
		arg.OldCommercialName,
		arg.OldLocationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticleStatus = `-- name: UpdateArticleStatus :one
UPDATE articles SET status = $1, expected_available_date = $2, updated_at = now()
WHERE id = $3 AND group_id = $4
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, image_path, description, instructions, purchase_date, purchase_price, place, created_at, updated_at, expected_available_date, approval_level, import_batch_id, manager_notes
`

type UpdateArticleStatusParams struct {
	Status                string      `json:"status"`
	ExpectedAvailableDate pgtype.Date `json:"expected_available_date"`
	ID                    pgtype.UUID `json:"id"`
	GroupID               string      `json:"group_id"`
}

func (q *Queries) UpdateArticleStatus(ctx context.Context, arg UpdateArticleStatusParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticleStatus,
		arg.Status,
		arg.ExpectedAvailableDate,
		arg.ID,
		arg.GroupID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ImagePath,
		&i.Description,
		&i.Instructions,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpectedAvailableDate,
		&i.ApprovalLevel,
		&i.ImportBatchID,
		&i.ManagerNotes,
	)
	return i, err
}
