// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookingItem = `-- name: AddBookingItem :one
INSERT INTO booking_items (group_id, booking_id, article_id)
VALUES ($1, $2, $3)
RETURNING id, group_id, booking_id, article_id, pickup_status, return_status, notes
`

type AddBookingItemParams struct {
	GroupID   string      `json:"group_id"`
	BookingID pgtype.UUID `json:"booking_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

func (q *Queries) AddBookingItem(ctx context.Context, arg AddBookingItemParams) (BookingItem, error) {
	row := q.db.QueryRow(ctx, addBookingItem, arg.GroupID, arg.BookingID, arg.ArticleID)
	var i BookingItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.BookingID,
		&i.ArticleID,
		&i.PickupStatus,
		&i.ReturnStatus,
		&i.Notes,
	)
	return i, err
}

const allItemsPickedUp = `-- name: AllItemsPickedUp :one
SELECT NOT EXISTS (
    SELECT 1 FROM booking_items
    WHERE booking_id = $1 AND group_id = $2
        AND pickup_status IS NULL
) AS all_picked_up
`

type AllItemsPickedUpParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	GroupID   string      `json:"group_id"`
}

// Returns true if every item in the booking has a non-null pickup_status.
func (q *Queries) AllItemsPickedUp(ctx context.Context, arg AllItemsPickedUpParams) (bool, error) {
	row := q.db.QueryRow(ctx, allItemsPickedUp, arg.BookingID, arg.GroupID)
	var all_picked_up bool
	err := row.Scan(&all_picked_up)
	return all_picked_up, err
}

const availableArticles = `-- name: AvailableArticles :many
SELECT a.id, a.commercial_name, a.common_name, a.category_id, a.location_id,
    l.name AS location_name, c.name AS category_name, a.place, a.status,
    a.individually_tracked, a.requires_approval
FROM articles a
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE a.group_id = $1
    AND a.status IN ('ok', 'reported_usable')
    AND a.id NOT IN (
        SELECT bi.article_id FROM booking_items bi
        JOIN bookings b ON bi.booking_id = b.id
        WHERE b.group_id = $1
            AND b.status IN ('draft', 'confirmed', 'picked_up', 'submitted', 'approved')
            AND b.start_date <= $2
            AND b.end_date >= $3
            AND (bi.return_status IS NULL OR bi.return_status = 'pending')
    )
ORDER BY a.commercial_name, a.common_name
`

type AvailableArticlesParams struct {
	GroupID   string      `json:"group_id"`
	EndDate   pgtype.Date `json:"end_date"`
	StartDate pgtype.Date `json:"start_date"`
}

type AvailableArticlesRow struct {
	ID                  pgtype.UUID `json:"id"`
	CommercialName      string      `json:"commercial_name"`
	CommonName          string      `json:"common_name"`
	CategoryID          pgtype.UUID `json:"category_id"`
	LocationID          pgtype.UUID `json:"location_id"`
	LocationName        string      `json:"location_name"`
	CategoryName        string      `json:"category_name"`
	Place               string      `json:"place"`
	Status              string      `json:"status"`
	IndividuallyTracked bool        `json:"individually_tracked"`
	RequiresApproval    bool        `json:"requires_approval"`
}

// Returns articles that are bookable and not reserved by overlapping bookings.
func (q *Queries) AvailableArticles(ctx context.Context, arg AvailableArticlesParams) ([]AvailableArticlesRow, error) {
	rows, err := q.db.Query(ctx, availableArticles, arg.GroupID, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableArticlesRow{}
	for rows.Next() {
		var i AvailableArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommercialName,
			&i.CommonName,
			&i.CategoryID,
			&i.LocationID,
			&i.LocationName,
			&i.CategoryName,
			&i.Place,
			&i.Status,
			&i.IndividuallyTracked,
			&i.RequiresApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const availableArticlesExcludingBooking = `-- name: AvailableArticlesExcludingBooking :many
SELECT a.id, a.commercial_name, a.common_name, a.location_id,
    l.name AS location_name, a.place, a.status,
    a.individually_tracked, a.requires_approval
FROM articles a
JOIN locations l ON a.location_id = l.id
WHERE a.group_id = $1
    AND a.status IN ('ok', 'reported_usable')
    AND a.id NOT IN (
        SELECT bi.article_id FROM booking_items bi
        JOIN bookings b ON bi.booking_id = b.id
        WHERE b.group_id = $1
            AND b.id != $2
            AND b.status IN ('draft', 'confirmed', 'picked_up', 'submitted', 'approved')
            AND b.start_date <= $3
            AND b.end_date >= $4
            AND (bi.return_status IS NULL OR bi.return_status = 'pending')
    )
    AND a.id NOT IN (
        SELECT bi.article_id FROM booking_items bi
        WHERE bi.booking_id = $2
    )
ORDER BY a.commercial_name, a.common_name
`

type AvailableArticlesExcludingBookingParams struct {
	GroupID          string      `json:"group_id"`
	ExcludeBookingID pgtype.UUID `json:"exclude_booking_id"`
	EndDate          pgtype.Date `json:"end_date"`
	StartDate        pgtype.Date `json:"start_date"`
}

type AvailableArticlesExcludingBookingRow struct {
	ID                  pgtype.UUID `json:"id"`
	CommercialName      string      `json:"commercial_name"`
	CommonName          string      `json:"common_name"`
	LocationID          pgtype.UUID `json:"location_id"`
	LocationName        string      `json:"location_name"`
	Place               string      `json:"place"`
	Status              string      `json:"status"`
	IndividuallyTracked bool        `json:"individually_tracked"`
	RequiresApproval    bool        `json:"requires_approval"`
}

// Same as AvailableArticles but excludes items already in the given booking.
func (q *Queries) AvailableArticlesExcludingBooking(ctx context.Context, arg AvailableArticlesExcludingBookingParams) ([]AvailableArticlesExcludingBookingRow, error) {
	rows, err := q.db.Query(ctx, availableArticlesExcludingBooking,
		arg.GroupID,
		arg.ExcludeBookingID,
		arg.EndDate,
		arg.StartDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailableArticlesExcludingBookingRow{}
	for rows.Next() {
		var i AvailableArticlesExcludingBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.CommercialName,
			&i.CommonName,
			&i.LocationID,
			&i.LocationName,
			&i.Place,
			&i.Status,
			&i.IndividuallyTracked,
			&i.RequiresApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookingHasApprovalRequired = `-- name: BookingHasApprovalRequired :one
SELECT EXISTS (
    SELECT 1 FROM booking_items bi
    JOIN articles a ON bi.article_id = a.id
    WHERE bi.booking_id = $1 AND bi.group_id = $2
        AND a.requires_approval = true
) AS requires_approval
`

type BookingHasApprovalRequiredParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	GroupID   string      `json:"group_id"`
}

// Returns true if any article in the booking requires approval.
func (q *Queries) BookingHasApprovalRequired(ctx context.Context, arg BookingHasApprovalRequiredParams) (bool, error) {
	row := q.db.QueryRow(ctx, bookingHasApprovalRequired, arg.BookingID, arg.GroupID)
	var requires_approval bool
	err := row.Scan(&requires_approval)
	return requires_approval, err
}

const cleanupStaleDrafts = `-- name: CleanupStaleDrafts :exec
DELETE FROM bookings
WHERE group_id = $1 AND status = 'draft'
    AND created_at < $2
`

type CleanupStaleDraftsParams struct {
	GroupID   string             `json:"group_id"`
	OlderThan pgtype.Timestamptz `json:"older_than"`
}

// Delete draft bookings older than the given threshold.
func (q *Queries) CleanupStaleDrafts(ctx context.Context, arg CleanupStaleDraftsParams) error {
	_, err := q.db.Exec(ctx, cleanupStaleDrafts, arg.GroupID, arg.OlderThan)
	return err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    group_id, created_by, used_by_unit_id, used_by_external,
    used_by_external_contact, status, start_date, end_date, notes
) VALUES (
    $1, $2, $3, $4,
    $5, 'draft', $6, $7, $8
)
RETURNING id, group_id, created_by, used_by_unit_id, used_by_external, used_by_external_contact, status, start_date, end_date, notes, created_at, updated_at
`

type CreateBookingParams struct {
	GroupID               string      `json:"group_id"`
	CreatedBy             string      `json:"created_by"`
	UsedByUnitID          pgtype.UUID `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text `json:"used_by_external"`
	UsedByExternalContact pgtype.Text `json:"used_by_external_contact"`
	StartDate             pgtype.Date `json:"start_date"`
	EndDate               pgtype.Date `json:"end_date"`
	Notes                 string      `json:"notes"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.GroupID,
		arg.CreatedBy,
		arg.UsedByUnitID,
		arg.UsedByExternal,
		arg.UsedByExternalContact,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.UsedByUnitID,
		&i.UsedByExternal,
		&i.UsedByExternalContact,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings
WHERE id = $1 AND group_id = $2 AND status = 'draft'
`

type DeleteBookingParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteBooking(ctx context.Context, arg DeleteBookingParams) error {
	_, err := q.db.Exec(ctx, deleteBooking, arg.ID, arg.GroupID)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT b.id, b.group_id, b.created_by, b.used_by_unit_id, b.used_by_external, b.used_by_external_contact, b.status, b.start_date, b.end_date, b.notes, b.created_at, b.updated_at, u.name AS unit_name
FROM bookings b
LEFT JOIN units u ON b.used_by_unit_id = u.id
WHERE b.id = $1 AND b.group_id = $2
`

type GetBookingParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetBookingRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CreatedBy             string             `json:"created_by"`
	UsedByUnitID          pgtype.UUID        `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text        `json:"used_by_external"`
	UsedByExternalContact pgtype.Text        `json:"used_by_external_contact"`
	Status                string             `json:"status"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UnitName              pgtype.Text        `json:"unit_name"`
}

func (q *Queries) GetBooking(ctx context.Context, arg GetBookingParams) (GetBookingRow, error) {
	row := q.db.QueryRow(ctx, getBooking, arg.ID, arg.GroupID)
	var i GetBookingRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.UsedByUnitID,
		&i.UsedByExternal,
		&i.UsedByExternalContact,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitName,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, group_id, name, gchat_webhook_url, created_at FROM units
WHERE id = $1 AND group_id = $2
`

type GetUnitByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetUnitByID(ctx context.Context, arg GetUnitByIDParams) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, arg.ID, arg.GroupID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingItems = `-- name: ListBookingItems :many
SELECT bi.id, bi.group_id, bi.booking_id, bi.article_id, bi.pickup_status, bi.return_status, bi.notes,
    a.commercial_name,
    a.common_name,
    a.place,
    a.requires_approval,
    a.individually_tracked,
    l.name AS location_name,
    c.name AS category_name
FROM booking_items bi
JOIN articles a ON bi.article_id = a.id
JOIN locations l ON a.location_id = l.id
JOIN categories c ON a.category_id = c.id
WHERE bi.booking_id = $1 AND bi.group_id = $2
ORDER BY c.name, a.commercial_name, a.common_name
`

type ListBookingItemsParams struct {
	BookingID pgtype.UUID `json:"booking_id"`
	GroupID   string      `json:"group_id"`
}

type ListBookingItemsRow struct {
	ID                  pgtype.UUID `json:"id"`
	GroupID             string      `json:"group_id"`
	BookingID           pgtype.UUID `json:"booking_id"`
	ArticleID           pgtype.UUID `json:"article_id"`
	PickupStatus        pgtype.Text `json:"pickup_status"`
	ReturnStatus        pgtype.Text `json:"return_status"`
	Notes               string      `json:"notes"`
	CommercialName      string      `json:"commercial_name"`
	CommonName          string      `json:"common_name"`
	Place               string      `json:"place"`
	RequiresApproval    bool        `json:"requires_approval"`
	IndividuallyTracked bool        `json:"individually_tracked"`
	LocationName        string      `json:"location_name"`
	CategoryName        string      `json:"category_name"`
}

func (q *Queries) ListBookingItems(ctx context.Context, arg ListBookingItemsParams) ([]ListBookingItemsRow, error) {
	rows, err := q.db.Query(ctx, listBookingItems, arg.BookingID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingItemsRow{}
	for rows.Next() {
		var i ListBookingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.BookingID,
			&i.ArticleID,
			&i.PickupStatus,
			&i.ReturnStatus,
			&i.Notes,
			&i.CommercialName,
			&i.CommonName,
			&i.Place,
			&i.RequiresApproval,
			&i.IndividuallyTracked,
			&i.LocationName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT b.id, b.group_id, b.created_by, b.used_by_unit_id, b.used_by_external, b.used_by_external_contact, b.status, b.start_date, b.end_date, b.notes, b.created_at, b.updated_at, u.name AS unit_name
FROM bookings b
LEFT JOIN units u ON b.used_by_unit_id = u.id
WHERE b.group_id = $1 AND b.status = $2
ORDER BY b.start_date
`

type ListBookingsByStatusParams struct {
	GroupID string `json:"group_id"`
	Status  string `json:"status"`
}

type ListBookingsByStatusRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CreatedBy             string             `json:"created_by"`
	UsedByUnitID          pgtype.UUID        `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text        `json:"used_by_external"`
	UsedByExternalContact pgtype.Text        `json:"used_by_external_contact"`
	Status                string             `json:"status"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UnitName              pgtype.Text        `json:"unit_name"`
}

func (q *Queries) ListBookingsByStatus(ctx context.Context, arg ListBookingsByStatusParams) ([]ListBookingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByStatus, arg.GroupID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByStatusRow{}
	for rows.Next() {
		var i ListBookingsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.UsedByUnitID,
			&i.UsedByExternal,
			&i.UsedByExternalContact,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT b.id, b.group_id, b.created_by, b.used_by_unit_id, b.used_by_external, b.used_by_external_contact, b.status, b.start_date, b.end_date, b.notes, b.created_at, b.updated_at, u.name AS unit_name
FROM bookings b
LEFT JOIN units u ON b.used_by_unit_id = u.id
WHERE b.group_id = $1
    AND (b.created_by = $2 OR b.used_by_unit_id = ANY(
        SELECT un.id FROM units un WHERE un.group_id = $1 AND un.name = ANY($3::text[])
    ))
ORDER BY b.created_at DESC
`

type ListBookingsByUserParams struct {
	GroupID   string   `json:"group_id"`
	UserID    string   `json:"user_id"`
	UnitNames []string `json:"unit_names"`
}

type ListBookingsByUserRow struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CreatedBy             string             `json:"created_by"`
	UsedByUnitID          pgtype.UUID        `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text        `json:"used_by_external"`
	UsedByExternalContact pgtype.Text        `json:"used_by_external_contact"`
	Status                string             `json:"status"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	UnitName              pgtype.Text        `json:"unit_name"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]ListBookingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.GroupID, arg.UserID, arg.UnitNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserRow{}
	for rows.Next() {
		var i ListBookingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.UsedByUnitID,
			&i.UsedByExternal,
			&i.UsedByExternalContact,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, group_id, name, gchat_webhook_url, created_at FROM units
WHERE group_id = $1
ORDER BY name
`

func (q *Queries) ListUnits(ctx context.Context, groupID string) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.GchatWebhookUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookingItem = `-- name: RemoveBookingItem :exec
DELETE FROM booking_items
WHERE id = $1 AND group_id = $2 AND booking_id = $3
`

type RemoveBookingItemParams struct {
	ID        pgtype.UUID `json:"id"`
	GroupID   string      `json:"group_id"`
	BookingID pgtype.UUID `json:"booking_id"`
}

func (q *Queries) RemoveBookingItem(ctx context.Context, arg RemoveBookingItemParams) error {
	_, err := q.db.Exec(ctx, removeBookingItem, arg.ID, arg.GroupID, arg.BookingID)
	return err
}

const swapBookingItemArticle = `-- name: SwapBookingItemArticle :one
UPDATE booking_items SET article_id = $1, pickup_status = 'swapped'
WHERE id = $2 AND group_id = $3 AND booking_id = $4
RETURNING id, group_id, booking_id, article_id, pickup_status, return_status, notes
`

type SwapBookingItemArticleParams struct {
	NewArticleID pgtype.UUID `json:"new_article_id"`
	ID           pgtype.UUID `json:"id"`
	GroupID      string      `json:"group_id"`
	BookingID    pgtype.UUID `json:"booking_id"`
}

func (q *Queries) SwapBookingItemArticle(ctx context.Context, arg SwapBookingItemArticleParams) (BookingItem, error) {
	row := q.db.QueryRow(ctx, swapBookingItemArticle,
		arg.NewArticleID,
		arg.ID,
		arg.GroupID,
		arg.BookingID,
	)
	var i BookingItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.BookingID,
		&i.ArticleID,
		&i.PickupStatus,
		&i.ReturnStatus,
		&i.Notes,
	)
	return i, err
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings SET
    start_date = $1,
    end_date = $2,
    used_by_unit_id = $3,
    used_by_external = $4,
    used_by_external_contact = $5,
    notes = $6,
    updated_at = now()
WHERE id = $7 AND group_id = $8
RETURNING id, group_id, created_by, used_by_unit_id, used_by_external, used_by_external_contact, status, start_date, end_date, notes, created_at, updated_at
`

type UpdateBookingParams struct {
	StartDate             pgtype.Date `json:"start_date"`
	EndDate               pgtype.Date `json:"end_date"`
	UsedByUnitID          pgtype.UUID `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text `json:"used_by_external"`
	UsedByExternalContact pgtype.Text `json:"used_by_external_contact"`
	Notes                 string      `json:"notes"`
	ID                    pgtype.UUID `json:"id"`
	GroupID               string      `json:"group_id"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBooking,
		arg.StartDate,
		arg.EndDate,
		arg.UsedByUnitID,
		arg.UsedByExternal,
		arg.UsedByExternalContact,
		arg.Notes,
		arg.ID,
		arg.GroupID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.UsedByUnitID,
		&i.UsedByExternal,
		&i.UsedByExternalContact,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingItemPickupStatus = `-- name: UpdateBookingItemPickupStatus :one
UPDATE booking_items SET pickup_status = $1
WHERE id = $2 AND group_id = $3 AND booking_id = $4
RETURNING id, group_id, booking_id, article_id, pickup_status, return_status, notes
`

type UpdateBookingItemPickupStatusParams struct {
	PickupStatus pgtype.Text `json:"pickup_status"`
	ID           pgtype.UUID `json:"id"`
	GroupID      string      `json:"group_id"`
	BookingID    pgtype.UUID `json:"booking_id"`
}

func (q *Queries) UpdateBookingItemPickupStatus(ctx context.Context, arg UpdateBookingItemPickupStatusParams) (BookingItem, error) {
	row := q.db.QueryRow(ctx, updateBookingItemPickupStatus,
		arg.PickupStatus,
		arg.ID,
		arg.GroupID,
		arg.BookingID,
	)
	var i BookingItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.BookingID,
		&i.ArticleID,
		&i.PickupStatus,
		&i.ReturnStatus,
		&i.Notes,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET status = $1, updated_at = now()
WHERE id = $2 AND group_id = $3
RETURNING id, group_id, created_by, used_by_unit_id, used_by_external, used_by_external_contact, status, start_date, end_date, notes, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	Status  string      `json:"status"`
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.Status, arg.ID, arg.GroupID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.UsedByUnitID,
		&i.UsedByExternal,
		&i.UsedByExternalContact,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
