// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (group_id, name, parent_id, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, name, parent_id, sort_order, created_at
`

type CreateCategoryParams struct {
	GroupID   string      `json:"group_id"`
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.GroupID,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND group_id = $2
`

type DeleteCategoryParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.GroupID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, group_id, name, parent_id, sort_order, created_at FROM categories
WHERE id = $1 AND group_id = $2
`

type GetCategoryParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.GroupID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, group_id, name, parent_id, sort_order, created_at FROM categories
WHERE group_id = $1 AND name = $2 AND parent_id IS NOT DISTINCT FROM $3
`

type GetCategoryByNameParams struct {
	GroupID  string      `json:"group_id"`
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.GroupID, arg.Name, arg.ParentID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, group_id, name, parent_id, sort_order, created_at FROM categories
WHERE group_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context, groupID string) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $1, parent_id = $2, sort_order = $3
WHERE id = $4 AND group_id = $5
RETURNING id, group_id, name, parent_id, sort_order, created_at
`

type UpdateCategoryParams struct {
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
	GroupID   string      `json:"group_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
		arg.GroupID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
