// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticlesForCategory = `-- name: CountArticlesForCategory :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND category_id = $2
`

type CountArticlesForCategoryParams struct {
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CountArticlesForCategory(ctx context.Context, arg CountArticlesForCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForCategory, arg.GroupID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesForLocation = `-- name: CountArticlesForLocation :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND location_id = $2
`

type CountArticlesForLocationParams struct {
	GroupID    string      `json:"group_id"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) CountArticlesForLocation(ctx context.Context, arg CountArticlesForLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForLocation, arg.GroupID, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupSettings = `-- name: GetGroupSettings :one
SELECT group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, created_at, updated_at, image_upload_role FROM group_settings
WHERE group_id = $1
`

func (q *Queries) GetGroupSettings(ctx context.Context, groupID string) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, getGroupSettings, groupID)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.GchatWebhookUrl,
		&i.DefaultApprovalLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUploadRole,
	)
	return i, err
}

const upsertGroupSettings = `-- name: UpsertGroupSettings :one
INSERT INTO group_settings (group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, image_upload_role)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (group_id) DO UPDATE SET
    notification_email_from = $2,
    smtp_key_encrypted = $3,
    gchat_webhook_url = $4,
    default_approval_level = $5,
    image_upload_role = $6,
    updated_at = now()
RETURNING group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, created_at, updated_at, image_upload_role
`

type UpsertGroupSettingsParams struct {
	GroupID               string `json:"group_id"`
	NotificationEmailFrom string `json:"notification_email_from"`
	SmtpKeyEncrypted      []byte `json:"smtp_key_encrypted"`
	GchatWebhookUrl       string `json:"gchat_webhook_url"`
	DefaultApprovalLevel  string `json:"default_approval_level"`
	ImageUploadRole       string `json:"image_upload_role"`
}

func (q *Queries) UpsertGroupSettings(ctx context.Context, arg UpsertGroupSettingsParams) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, upsertGroupSettings,
		arg.GroupID,
		arg.NotificationEmailFrom,
		arg.SmtpKeyEncrypted,
		arg.GchatWebhookUrl,
		arg.DefaultApprovalLevel,
		arg.ImageUploadRole,
	)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.GchatWebhookUrl,
		&i.DefaultApprovalLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUploadRole,
	)
	return i, err
}
