// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_settings.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllGchatSpacesForGroup = `-- name: ClearAllGchatSpacesForGroup :exec
UPDATE teams SET gchat_space_id = NULL
WHERE group_id = $1
`

func (q *Queries) ClearAllGchatSpacesForGroup(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, clearAllGchatSpacesForGroup, groupID)
	return err
}

const clearGchatCredentials = `-- name: ClearGchatCredentials :exec
UPDATE group_settings SET
    gchat_service_account_json_encrypted = NULL,
    gchat_admin_email = '',
    updated_at = now()
WHERE group_id = $1
`

func (q *Queries) ClearGchatCredentials(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, clearGchatCredentials, groupID)
	return err
}

const clearGroupLogo = `-- name: ClearGroupLogo :exec
UPDATE group_settings SET logo_file_id = NULL, updated_at = now()
WHERE group_id = $1
`

func (q *Queries) ClearGroupLogo(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, clearGroupLogo, groupID)
	return err
}

const countArticlesForCategory = `-- name: CountArticlesForCategory :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND category_id = $2
`

type CountArticlesForCategoryParams struct {
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CountArticlesForCategory(ctx context.Context, arg CountArticlesForCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForCategory, arg.GroupID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesForLocation = `-- name: CountArticlesForLocation :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND location_id = $2
`

type CountArticlesForLocationParams struct {
	GroupID    string      `json:"group_id"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) CountArticlesForLocation(ctx context.Context, arg CountArticlesForLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForLocation, arg.GroupID, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupSettingsDefaults = `-- name: CreateGroupSettingsDefaults :one
INSERT INTO group_settings (group_id)
VALUES ($1)
ON CONFLICT (group_id) DO NOTHING
RETURNING group_id, notification_email_from, smtp_key_encrypted, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language, smtp_host, smtp_port, smtp_tls, smtp_user, notification_defaults, logo_file_id, enabled_channels, gchat_service_account_json_encrypted, gchat_admin_email, default_gruppkanal_channels
`

func (q *Queries) CreateGroupSettingsDefaults(ctx context.Context, groupID string) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, createGroupSettingsDefaults, groupID)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUser,
		&i.NotificationDefaults,
		&i.LogoFileID,
		&i.EnabledChannels,
		&i.GchatServiceAccountJsonEncrypted,
		&i.GchatAdminEmail,
		&i.DefaultGruppkanalChannels,
	)
	return i, err
}

const getGchatCredentials = `-- name: GetGchatCredentials :one
SELECT gchat_service_account_json_encrypted, gchat_admin_email FROM group_settings
WHERE group_id = $1
`

type GetGchatCredentialsRow struct {
	GchatServiceAccountJsonEncrypted []byte `json:"gchat_service_account_json_encrypted"`
	GchatAdminEmail                  string `json:"gchat_admin_email"`
}

func (q *Queries) GetGchatCredentials(ctx context.Context, groupID string) (GetGchatCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getGchatCredentials, groupID)
	var i GetGchatCredentialsRow
	err := row.Scan(&i.GchatServiceAccountJsonEncrypted, &i.GchatAdminEmail)
	return i, err
}

const getGroupLogoFileID = `-- name: GetGroupLogoFileID :one
SELECT logo_file_id FROM group_settings WHERE group_id = $1
`

func (q *Queries) GetGroupLogoFileID(ctx context.Context, groupID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGroupLogoFileID, groupID)
	var logo_file_id pgtype.UUID
	err := row.Scan(&logo_file_id)
	return logo_file_id, err
}

const getGroupNotificationDefaults = `-- name: GetGroupNotificationDefaults :one
SELECT notification_defaults, default_gruppkanal_channels FROM group_settings
WHERE group_id = $1
`

type GetGroupNotificationDefaultsRow struct {
	NotificationDefaults      json.RawMessage `json:"notification_defaults"`
	DefaultGruppkanalChannels []string        `json:"default_gruppkanal_channels"`
}

func (q *Queries) GetGroupNotificationDefaults(ctx context.Context, groupID string) (GetGroupNotificationDefaultsRow, error) {
	row := q.db.QueryRow(ctx, getGroupNotificationDefaults, groupID)
	var i GetGroupNotificationDefaultsRow
	err := row.Scan(&i.NotificationDefaults, &i.DefaultGruppkanalChannels)
	return i, err
}

const getGroupSettings = `-- name: GetGroupSettings :one
SELECT group_id, notification_email_from, smtp_key_encrypted, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language, smtp_host, smtp_port, smtp_tls, smtp_user, notification_defaults, logo_file_id, enabled_channels, gchat_service_account_json_encrypted, gchat_admin_email, default_gruppkanal_channels FROM group_settings
WHERE group_id = $1
`

func (q *Queries) GetGroupSettings(ctx context.Context, groupID string) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, getGroupSettings, groupID)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUser,
		&i.NotificationDefaults,
		&i.LogoFileID,
		&i.EnabledChannels,
		&i.GchatServiceAccountJsonEncrypted,
		&i.GchatAdminEmail,
		&i.DefaultGruppkanalChannels,
	)
	return i, err
}

const setGchatCredentials = `-- name: SetGchatCredentials :exec
UPDATE group_settings SET
    gchat_service_account_json_encrypted = $1,
    gchat_admin_email = $2,
    updated_at = now()
WHERE group_id = $3
`

type SetGchatCredentialsParams struct {
	GchatServiceAccountJsonEncrypted []byte `json:"gchat_service_account_json_encrypted"`
	GchatAdminEmail                  string `json:"gchat_admin_email"`
	GroupID                          string `json:"group_id"`
}

func (q *Queries) SetGchatCredentials(ctx context.Context, arg SetGchatCredentialsParams) error {
	_, err := q.db.Exec(ctx, setGchatCredentials, arg.GchatServiceAccountJsonEncrypted, arg.GchatAdminEmail, arg.GroupID)
	return err
}

const setGroupLogo = `-- name: SetGroupLogo :exec
UPDATE group_settings SET logo_file_id = $1, updated_at = now()
WHERE group_id = $2
`

type SetGroupLogoParams struct {
	LogoFileID pgtype.UUID `json:"logo_file_id"`
	GroupID    string      `json:"group_id"`
}

func (q *Queries) SetGroupLogo(ctx context.Context, arg SetGroupLogoParams) error {
	_, err := q.db.Exec(ctx, setGroupLogo, arg.LogoFileID, arg.GroupID)
	return err
}

const setGroupNotificationDefaults = `-- name: SetGroupNotificationDefaults :exec
UPDATE group_settings SET
    notification_defaults = $1,
    default_gruppkanal_channels = $2,
    updated_at = now()
WHERE group_id = $3
`

type SetGroupNotificationDefaultsParams struct {
	NotificationDefaults      json.RawMessage `json:"notification_defaults"`
	DefaultGruppkanalChannels []string        `json:"default_gruppkanal_channels"`
	GroupID                   string          `json:"group_id"`
}

func (q *Queries) SetGroupNotificationDefaults(ctx context.Context, arg SetGroupNotificationDefaultsParams) error {
	_, err := q.db.Exec(ctx, setGroupNotificationDefaults, arg.NotificationDefaults, arg.DefaultGruppkanalChannels, arg.GroupID)
	return err
}

const updateEnabledChannels = `-- name: UpdateEnabledChannels :exec
UPDATE group_settings SET enabled_channels = $1, updated_at = now()
WHERE group_id = $2
`

type UpdateEnabledChannelsParams struct {
	EnabledChannels []string `json:"enabled_channels"`
	GroupID         string   `json:"group_id"`
}

func (q *Queries) UpdateEnabledChannels(ctx context.Context, arg UpdateEnabledChannelsParams) error {
	_, err := q.db.Exec(ctx, updateEnabledChannels, arg.EnabledChannels, arg.GroupID)
	return err
}

const updateSmtpSettings = `-- name: UpdateSmtpSettings :one
UPDATE group_settings SET
    notification_email_from = $1,
    smtp_host = $2,
    smtp_port = $3,
    smtp_tls = $4,
    smtp_user = $5,
    updated_at = now()
WHERE group_id = $6
RETURNING group_id, notification_email_from, smtp_key_encrypted, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language, smtp_host, smtp_port, smtp_tls, smtp_user, notification_defaults, logo_file_id, enabled_channels, gchat_service_account_json_encrypted, gchat_admin_email, default_gruppkanal_channels
`

type UpdateSmtpSettingsParams struct {
	NotificationEmailFrom string `json:"notification_email_from"`
	SmtpHost              string `json:"smtp_host"`
	SmtpPort              int32  `json:"smtp_port"`
	SmtpTls               string `json:"smtp_tls"`
	SmtpUser              string `json:"smtp_user"`
	GroupID               string `json:"group_id"`
}

func (q *Queries) UpdateSmtpSettings(ctx context.Context, arg UpdateSmtpSettingsParams) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, updateSmtpSettings,
		arg.NotificationEmailFrom,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpTls,
		arg.SmtpUser,
		arg.GroupID,
	)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUser,
		&i.NotificationDefaults,
		&i.LogoFileID,
		&i.EnabledChannels,
		&i.GchatServiceAccountJsonEncrypted,
		&i.GchatAdminEmail,
		&i.DefaultGruppkanalChannels,
	)
	return i, err
}

const upsertGroupSettings = `-- name: UpsertGroupSettings :one
INSERT INTO group_settings (
    group_id, notification_email_from, smtp_key_encrypted,
    default_approval_level, default_access_unknown, default_access_troop,
    default_access_role, image_upload_role, booking_role, article_edit_role,
    issue_resolve_role, manager_notes_role, default_language
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
ON CONFLICT (group_id) DO UPDATE SET
    notification_email_from = $2,
    smtp_key_encrypted = $3,
    default_approval_level = $4,
    default_access_unknown = $5,
    default_access_troop = $6,
    default_access_role = $7,
    image_upload_role = $8,
    booking_role = $9,
    article_edit_role = $10,
    issue_resolve_role = $11,
    manager_notes_role = $12,
    default_language = $13,
    updated_at = now()
RETURNING group_id, notification_email_from, smtp_key_encrypted, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language, smtp_host, smtp_port, smtp_tls, smtp_user, notification_defaults, logo_file_id, enabled_channels, gchat_service_account_json_encrypted, gchat_admin_email, default_gruppkanal_channels
`

type UpsertGroupSettingsParams struct {
	GroupID               string `json:"group_id"`
	NotificationEmailFrom string `json:"notification_email_from"`
	SmtpKeyEncrypted      []byte `json:"smtp_key_encrypted"`
	DefaultApprovalLevel  string `json:"default_approval_level"`
	DefaultAccessUnknown  string `json:"default_access_unknown"`
	DefaultAccessTroop    string `json:"default_access_troop"`
	DefaultAccessRole     string `json:"default_access_role"`
	ImageUploadRole       string `json:"image_upload_role"`
	BookingRole           string `json:"booking_role"`
	ArticleEditRole       string `json:"article_edit_role"`
	IssueResolveRole      string `json:"issue_resolve_role"`
	ManagerNotesRole      string `json:"manager_notes_role"`
	DefaultLanguage       string `json:"default_language"`
}

func (q *Queries) UpsertGroupSettings(ctx context.Context, arg UpsertGroupSettingsParams) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, upsertGroupSettings,
		arg.GroupID,
		arg.NotificationEmailFrom,
		arg.SmtpKeyEncrypted,
		arg.DefaultApprovalLevel,
		arg.DefaultAccessUnknown,
		arg.DefaultAccessTroop,
		arg.DefaultAccessRole,
		arg.ImageUploadRole,
		arg.BookingRole,
		arg.ArticleEditRole,
		arg.IssueResolveRole,
		arg.ManagerNotesRole,
		arg.DefaultLanguage,
	)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpTls,
		&i.SmtpUser,
		&i.NotificationDefaults,
		&i.LogoFileID,
		&i.EnabledChannels,
		&i.GchatServiceAccountJsonEncrypted,
		&i.GchatAdminEmail,
		&i.DefaultGruppkanalChannels,
	)
	return i, err
}
