// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
RETURNING id, name, created_at
`

type CreateGroupParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateGroupName = `-- name: UpdateGroupName :one
UPDATE groups SET name = $1
WHERE id = $2
RETURNING id, name, created_at
`

type UpdateGroupNameParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupName, arg.Name, arg.ID)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
