// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticlesForCategory = `-- name: CountArticlesForCategory :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND category_id = $2
`

type CountArticlesForCategoryParams struct {
	GroupID    string      `json:"group_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CountArticlesForCategory(ctx context.Context, arg CountArticlesForCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForCategory, arg.GroupID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesForLocation = `-- name: CountArticlesForLocation :one
SELECT count(*) FROM articles
WHERE group_id = $1 AND location_id = $2
`

type CountArticlesForLocationParams struct {
	GroupID    string      `json:"group_id"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) CountArticlesForLocation(ctx context.Context, arg CountArticlesForLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesForLocation, arg.GroupID, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupSettingsDefaults = `-- name: CreateGroupSettingsDefaults :one
INSERT INTO group_settings (group_id)
VALUES ($1)
ON CONFLICT (group_id) DO NOTHING
RETURNING group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language
`

func (q *Queries) CreateGroupSettingsDefaults(ctx context.Context, groupID string) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, createGroupSettingsDefaults, groupID)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.GchatWebhookUrl,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
	)
	return i, err
}

const getGroupSettings = `-- name: GetGroupSettings :one
SELECT group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language FROM group_settings
WHERE group_id = $1
`

func (q *Queries) GetGroupSettings(ctx context.Context, groupID string) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, getGroupSettings, groupID)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.GchatWebhookUrl,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
	)
	return i, err
}

const upsertGroupSettings = `-- name: UpsertGroupSettings :one
INSERT INTO group_settings (
    group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url,
    default_approval_level, default_access_unknown, default_access_troop,
    default_access_role, image_upload_role, booking_role, article_edit_role,
    issue_resolve_role, manager_notes_role, default_language
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (group_id) DO UPDATE SET
    notification_email_from = $2,
    smtp_key_encrypted = $3,
    gchat_webhook_url = $4,
    default_approval_level = $5,
    default_access_unknown = $6,
    default_access_troop = $7,
    default_access_role = $8,
    image_upload_role = $9,
    booking_role = $10,
    article_edit_role = $11,
    issue_resolve_role = $12,
    manager_notes_role = $13,
    default_language = $14,
    updated_at = now()
RETURNING group_id, notification_email_from, smtp_key_encrypted, gchat_webhook_url, default_approval_level, default_access_unknown, default_access_troop, default_access_role, image_upload_role, booking_role, article_edit_role, issue_resolve_role, manager_notes_role, created_at, updated_at, default_language
`

type UpsertGroupSettingsParams struct {
	GroupID               string `json:"group_id"`
	NotificationEmailFrom string `json:"notification_email_from"`
	SmtpKeyEncrypted      []byte `json:"smtp_key_encrypted"`
	GchatWebhookUrl       string `json:"gchat_webhook_url"`
	DefaultApprovalLevel  string `json:"default_approval_level"`
	DefaultAccessUnknown  string `json:"default_access_unknown"`
	DefaultAccessTroop    string `json:"default_access_troop"`
	DefaultAccessRole     string `json:"default_access_role"`
	ImageUploadRole       string `json:"image_upload_role"`
	BookingRole           string `json:"booking_role"`
	ArticleEditRole       string `json:"article_edit_role"`
	IssueResolveRole      string `json:"issue_resolve_role"`
	ManagerNotesRole      string `json:"manager_notes_role"`
	DefaultLanguage       string `json:"default_language"`
}

func (q *Queries) UpsertGroupSettings(ctx context.Context, arg UpsertGroupSettingsParams) (GroupSetting, error) {
	row := q.db.QueryRow(ctx, upsertGroupSettings,
		arg.GroupID,
		arg.NotificationEmailFrom,
		arg.SmtpKeyEncrypted,
		arg.GchatWebhookUrl,
		arg.DefaultApprovalLevel,
		arg.DefaultAccessUnknown,
		arg.DefaultAccessTroop,
		arg.DefaultAccessRole,
		arg.ImageUploadRole,
		arg.BookingRole,
		arg.ArticleEditRole,
		arg.IssueResolveRole,
		arg.ManagerNotesRole,
		arg.DefaultLanguage,
	)
	var i GroupSetting
	err := row.Scan(
		&i.GroupID,
		&i.NotificationEmailFrom,
		&i.SmtpKeyEncrypted,
		&i.GchatWebhookUrl,
		&i.DefaultApprovalLevel,
		&i.DefaultAccessUnknown,
		&i.DefaultAccessTroop,
		&i.DefaultAccessRole,
		&i.ImageUploadRole,
		&i.BookingRole,
		&i.ArticleEditRole,
		&i.IssueResolveRole,
		&i.ManagerNotesRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLanguage,
	)
	return i, err
}
