// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssueReport = `-- name: CreateIssueReport :one
INSERT INTO issue_reports (
    group_id, article_id, reporter_id, description, severity, status
) VALUES (
    $1, $2, $3, $4, $5, 'open'
)
RETURNING id, group_id, article_id, reporter_id, description, severity, status, resolution, resolved_by, created_at, resolved_at
`

type CreateIssueReportParams struct {
	GroupID     string      `json:"group_id"`
	ArticleID   pgtype.UUID `json:"article_id"`
	ReporterID  string      `json:"reporter_id"`
	Description string      `json:"description"`
	Severity    string      `json:"severity"`
}

func (q *Queries) CreateIssueReport(ctx context.Context, arg CreateIssueReportParams) (IssueReport, error) {
	row := q.db.QueryRow(ctx, createIssueReport,
		arg.GroupID,
		arg.ArticleID,
		arg.ReporterID,
		arg.Description,
		arg.Severity,
	)
	var i IssueReport
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArticleID,
		&i.ReporterID,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getIssueReport = `-- name: GetIssueReport :one
SELECT ir.id, ir.group_id, ir.article_id, ir.reporter_id, ir.description, ir.severity, ir.status, ir.resolution, ir.resolved_by, ir.created_at, ir.resolved_at,
    a.commercial_name,
    a.common_name,
    u.name AS reporter_name
FROM issue_reports ir
JOIN articles a ON ir.article_id = a.id
JOIN users u ON ir.reporter_id = u.id
WHERE ir.id = $1 AND ir.group_id = $2
`

type GetIssueReportParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetIssueReportRow struct {
	ID             pgtype.UUID        `json:"id"`
	GroupID        string             `json:"group_id"`
	ArticleID      pgtype.UUID        `json:"article_id"`
	ReporterID     string             `json:"reporter_id"`
	Description    string             `json:"description"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	Resolution     pgtype.Text        `json:"resolution"`
	ResolvedBy     pgtype.Text        `json:"resolved_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CommercialName string             `json:"commercial_name"`
	CommonName     string             `json:"common_name"`
	ReporterName   string             `json:"reporter_name"`
}

func (q *Queries) GetIssueReport(ctx context.Context, arg GetIssueReportParams) (GetIssueReportRow, error) {
	row := q.db.QueryRow(ctx, getIssueReport, arg.ID, arg.GroupID)
	var i GetIssueReportRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ArticleID,
		&i.ReporterID,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.Resolution,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.CommercialName,
		&i.CommonName,
		&i.ReporterName,
	)
	return i, err
}

const listIssueReports = `-- name: ListIssueReports :many
SELECT ir.id, ir.group_id, ir.article_id, ir.reporter_id, ir.description, ir.severity, ir.status, ir.resolution, ir.resolved_by, ir.created_at, ir.resolved_at,
    a.commercial_name,
    a.common_name,
    u.name AS reporter_name
FROM issue_reports ir
JOIN articles a ON ir.article_id = a.id
JOIN users u ON ir.reporter_id = u.id
WHERE ir.group_id = $1
    AND ($2::text IS NULL OR ir.status = $2)
ORDER BY ir.created_at DESC
`

type ListIssueReportsParams struct {
	GroupID string      `json:"group_id"`
	Status  pgtype.Text `json:"status"`
}

type ListIssueReportsRow struct {
	ID             pgtype.UUID        `json:"id"`
	GroupID        string             `json:"group_id"`
	ArticleID      pgtype.UUID        `json:"article_id"`
	ReporterID     string             `json:"reporter_id"`
	Description    string             `json:"description"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	Resolution     pgtype.Text        `json:"resolution"`
	ResolvedBy     pgtype.Text        `json:"resolved_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CommercialName string             `json:"commercial_name"`
	CommonName     string             `json:"common_name"`
	ReporterName   string             `json:"reporter_name"`
}

func (q *Queries) ListIssueReports(ctx context.Context, arg ListIssueReportsParams) ([]ListIssueReportsRow, error) {
	rows, err := q.db.Query(ctx, listIssueReports, arg.GroupID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueReportsRow{}
	for rows.Next() {
		var i ListIssueReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ArticleID,
			&i.ReporterID,
			&i.Description,
			&i.Severity,
			&i.Status,
			&i.Resolution,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.CommercialName,
			&i.CommonName,
			&i.ReporterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
