// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueArticle = `-- name: AddIssueArticle :exec
INSERT INTO issue_articles (issue_id, article_id, group_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddIssueArticleParams struct {
	IssueID   pgtype.UUID `json:"issue_id"`
	ArticleID pgtype.UUID `json:"article_id"`
	GroupID   string      `json:"group_id"`
}

func (q *Queries) AddIssueArticle(ctx context.Context, arg AddIssueArticleParams) error {
	_, err := q.db.Exec(ctx, addIssueArticle, arg.IssueID, arg.ArticleID, arg.GroupID)
	return err
}

const addIssueAssignee = `-- name: AddIssueAssignee :exec
INSERT INTO issue_assignees (issue_id, user_id, group_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddIssueAssigneeParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	UserID  string      `json:"user_id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) AddIssueAssignee(ctx context.Context, arg AddIssueAssigneeParams) error {
	_, err := q.db.Exec(ctx, addIssueAssignee, arg.IssueID, arg.UserID, arg.GroupID)
	return err
}

const archiveOpenIssuesForArticle = `-- name: ArchiveOpenIssuesForArticle :exec
UPDATE issue_reports ir SET status = 'archived', updated_at = now()
WHERE ir.group_id = $1
  AND ir.status IN ('open', 'in_progress')
  AND ir.id IN (
      SELECT ia1.issue_id FROM issue_articles ia1
      WHERE ia1.article_id = $2 AND ia1.group_id = $1
  )
  AND ir.id NOT IN (
      SELECT ia2.issue_id FROM issue_articles ia2
      JOIN articles a ON ia2.article_id = a.id
      WHERE ia2.group_id = $1 AND ia2.article_id != $2 AND a.status != 'archived'
  )
`

type ArchiveOpenIssuesForArticleParams struct {
	GroupID   string      `json:"group_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

// When an article is archived, close all open/in_progress issues linked only to it.
// Issues linked to other non-archived articles are left open.
func (q *Queries) ArchiveOpenIssuesForArticle(ctx context.Context, arg ArchiveOpenIssuesForArticleParams) error {
	_, err := q.db.Exec(ctx, archiveOpenIssuesForArticle, arg.GroupID, arg.ArticleID)
	return err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issue_reports (group_id, title, description, severity, reporter_id, booking_id)
VALUES ($1, $2, $3, $4, $5, $6::uuid)
RETURNING id, group_id, title, description, severity, status, reporter_id, booking_id, created_at, updated_at
`

type CreateIssueParams struct {
	GroupID     string      `json:"group_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Severity    string      `json:"severity"`
	ReporterID  string      `json:"reporter_id"`
	BookingID   pgtype.UUID `json:"booking_id"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (IssueReport, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.ReporterID,
		arg.BookingID,
	)
	var i IssueReport
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.ReporterID,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIssueEvent = `-- name: CreateIssueEvent :one
INSERT INTO issue_events (issue_id, group_id, actor_id, event_type, description, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, issue_id, group_id, actor_id, event_type, description, metadata, created_at
`

type CreateIssueEventParams struct {
	IssueID     pgtype.UUID     `json:"issue_id"`
	GroupID     string          `json:"group_id"`
	ActorID     string          `json:"actor_id"`
	EventType   string          `json:"event_type"`
	Description string          `json:"description"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateIssueEvent(ctx context.Context, arg CreateIssueEventParams) (IssueEvent, error) {
	row := q.db.QueryRow(ctx, createIssueEvent,
		arg.IssueID,
		arg.GroupID,
		arg.ActorID,
		arg.EventType,
		arg.Description,
		arg.Metadata,
	)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.GroupID,
		&i.ActorID,
		&i.EventType,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deriveArticleStatus = `-- name: DeriveArticleStatus :one
SELECT CASE
    WHEN EXISTS (
        SELECT 1 FROM issue_articles ia
        JOIN issue_reports ir ON ia.issue_id = ir.id
        WHERE ia.article_id = $1 AND ia.group_id = $2
          AND ir.status IN ('open', 'in_progress') AND ir.severity = 'missing'
    ) THEN 'reported_missing'
    WHEN EXISTS (
        SELECT 1 FROM issue_articles ia
        JOIN issue_reports ir ON ia.issue_id = ir.id
        WHERE ia.article_id = $1 AND ia.group_id = $2
          AND ir.status IN ('open', 'in_progress') AND ir.severity = 'unusable'
    ) THEN 'reported_unusable'
    WHEN EXISTS (
        SELECT 1 FROM issue_articles ia
        JOIN issue_reports ir ON ia.issue_id = ir.id
        WHERE ia.article_id = $1 AND ia.group_id = $2
          AND ir.status IN ('open', 'in_progress') AND ir.severity = 'usable'
    ) THEN 'reported_usable'
    ELSE 'ok'
END AS derived_status
`

type DeriveArticleStatusParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	GroupID   string      `json:"group_id"`
}

// Re-derives article status from its open issues.
// Returns the new status that should be stored.
// Priority: missing = unusable > usable > ok (missing takes precedence for tiebreak).
func (q *Queries) DeriveArticleStatus(ctx context.Context, arg DeriveArticleStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, deriveArticleStatus, arg.ArticleID, arg.GroupID)
	var derived_status string
	err := row.Scan(&derived_status)
	return derived_status, err
}

const getArticleCurrentStatus = `-- name: GetArticleCurrentStatus :one
SELECT status FROM articles WHERE id = $1 AND group_id = $2
`

type GetArticleCurrentStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetArticleCurrentStatus(ctx context.Context, arg GetArticleCurrentStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, getArticleCurrentStatus, arg.ID, arg.GroupID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getIssue = `-- name: GetIssue :one
SELECT
    ir.id, ir.group_id, ir.title, ir.description, ir.severity, ir.status, ir.reporter_id, ir.booking_id, ir.created_at, ir.updated_at,
    u.name AS reporter_name
FROM issue_reports ir
JOIN users u ON ir.reporter_id = u.id
WHERE ir.id = $1 AND ir.group_id = $2
`

type GetIssueParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetIssueRow struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      string             `json:"group_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Severity     string             `json:"severity"`
	Status       string             `json:"status"`
	ReporterID   string             `json:"reporter_id"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReporterName string             `json:"reporter_name"`
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ID, arg.GroupID)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.ReporterID,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReporterName,
	)
	return i, err
}

const listIssueArticles = `-- name: ListIssueArticles :many
SELECT
    a.id,
    a.commercial_name,
    a.common_name,
    l.name AS location_name,
    a.individually_tracked
FROM issue_articles ia
JOIN articles a ON ia.article_id = a.id
JOIN locations l ON a.location_id = l.id
WHERE ia.issue_id = $1 AND ia.group_id = $2
`

type ListIssueArticlesParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	GroupID string      `json:"group_id"`
}

type ListIssueArticlesRow struct {
	ID                  pgtype.UUID `json:"id"`
	CommercialName      string      `json:"commercial_name"`
	CommonName          string      `json:"common_name"`
	LocationName        string      `json:"location_name"`
	IndividuallyTracked bool        `json:"individually_tracked"`
}

func (q *Queries) ListIssueArticles(ctx context.Context, arg ListIssueArticlesParams) ([]ListIssueArticlesRow, error) {
	rows, err := q.db.Query(ctx, listIssueArticles, arg.IssueID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueArticlesRow{}
	for rows.Next() {
		var i ListIssueArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommercialName,
			&i.CommonName,
			&i.LocationName,
			&i.IndividuallyTracked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAssignees = `-- name: ListIssueAssignees :many
SELECT
    ia.user_id,
    ia.assigned_at,
    u.name AS user_name
FROM issue_assignees ia
JOIN users u ON ia.user_id = u.id
WHERE ia.issue_id = $1 AND ia.group_id = $2
`

type ListIssueAssigneesParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	GroupID string      `json:"group_id"`
}

type ListIssueAssigneesRow struct {
	UserID     string             `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	UserName   string             `json:"user_name"`
}

func (q *Queries) ListIssueAssignees(ctx context.Context, arg ListIssueAssigneesParams) ([]ListIssueAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listIssueAssignees, arg.IssueID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueAssigneesRow{}
	for rows.Next() {
		var i ListIssueAssigneesRow
		if err := rows.Scan(&i.UserID, &i.AssignedAt, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueEvents = `-- name: ListIssueEvents :many
SELECT
    ie.id, ie.issue_id, ie.group_id, ie.actor_id, ie.event_type, ie.description, ie.metadata, ie.created_at,
    u.name AS actor_name
FROM issue_events ie
JOIN users u ON ie.actor_id = u.id
WHERE ie.issue_id = $1 AND ie.group_id = $2
ORDER BY ie.created_at ASC
`

type ListIssueEventsParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	GroupID string      `json:"group_id"`
}

type ListIssueEventsRow struct {
	ID          pgtype.UUID        `json:"id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	GroupID     string             `json:"group_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	Description string             `json:"description"`
	Metadata    json.RawMessage    `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorName   string             `json:"actor_name"`
}

func (q *Queries) ListIssueEvents(ctx context.Context, arg ListIssueEventsParams) ([]ListIssueEventsRow, error) {
	rows, err := q.db.Query(ctx, listIssueEvents, arg.IssueID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueEventsRow{}
	for rows.Next() {
		var i ListIssueEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.GroupID,
			&i.ActorID,
			&i.EventType,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT
    ir.id, ir.group_id, ir.title, ir.description, ir.severity, ir.status, ir.reporter_id, ir.booking_id, ir.created_at, ir.updated_at,
    u.name AS reporter_name
FROM issue_reports ir
JOIN users u ON ir.reporter_id = u.id
WHERE ir.group_id = $1
    AND (COALESCE(array_length($2::text[], 1), 0) = 0 OR ir.status = ANY($2::text[]))
    AND (NOT $3::bool OR (
        ir.reporter_id = $4
        OR ir.id IN (
            SELECT issue_id FROM issue_assignees WHERE user_id = $4 AND group_id = $1
        )
        OR ir.id IN (
            SELECT issue_id FROM issue_events WHERE actor_id = $4 AND group_id = $1
        )
    ))
    AND ($5::uuid IS NULL OR ir.id IN (
        SELECT issue_id FROM issue_articles WHERE article_id = $5 AND group_id = $1
    ))
ORDER BY ir.updated_at DESC, ir.created_at DESC
`

type ListIssuesParams struct {
	GroupID   string      `json:"group_id"`
	Statuses  []string    `json:"statuses"`
	Mine      bool        `json:"mine"`
	UserID    string      `json:"user_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

type ListIssuesRow struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      string             `json:"group_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Severity     string             `json:"severity"`
	Status       string             `json:"status"`
	ReporterID   string             `json:"reporter_id"`
	BookingID    pgtype.UUID        `json:"booking_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReporterName string             `json:"reporter_name"`
}

// Filters: status (comma-separated via array), mine (reporter_id = user_id OR assigned),
// article_id (linked articles).
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.GroupID,
		arg.Statuses,
		arg.Mine,
		arg.UserID,
		arg.ArticleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.Status,
			&i.ReporterID,
			&i.BookingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReporterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssueArticles = `-- name: ListOpenIssueArticles :many
SELECT ia.article_id
FROM issue_articles ia
WHERE ia.issue_id = $1 AND ia.group_id = $2
`

type ListOpenIssueArticlesParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	GroupID string      `json:"group_id"`
}

// Returns all article IDs linked to a specific issue that are currently open/in_progress.
func (q *Queries) ListOpenIssueArticles(ctx context.Context, arg ListOpenIssueArticlesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOpenIssueArticles, arg.IssueID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var article_id pgtype.UUID
		if err := rows.Scan(&article_id); err != nil {
			return nil, err
		}
		items = append(items, article_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIssueArticle = `-- name: RemoveIssueArticle :exec
DELETE FROM issue_articles
WHERE issue_id = $1 AND article_id = $2 AND group_id = $3
`

type RemoveIssueArticleParams struct {
	IssueID   pgtype.UUID `json:"issue_id"`
	ArticleID pgtype.UUID `json:"article_id"`
	GroupID   string      `json:"group_id"`
}

func (q *Queries) RemoveIssueArticle(ctx context.Context, arg RemoveIssueArticleParams) error {
	_, err := q.db.Exec(ctx, removeIssueArticle, arg.IssueID, arg.ArticleID, arg.GroupID)
	return err
}

const replaceIssueAssignees = `-- name: ReplaceIssueAssignees :exec
DELETE FROM issue_assignees WHERE issue_id = $1 AND group_id = $2
`

type ReplaceIssueAssigneesParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	GroupID string      `json:"group_id"`
}

// Caller should do delete + insert in a transaction; this deletes all first.
func (q *Queries) ReplaceIssueAssignees(ctx context.Context, arg ReplaceIssueAssigneesParams) error {
	_, err := q.db.Exec(ctx, replaceIssueAssignees, arg.IssueID, arg.GroupID)
	return err
}

const updateArticleStatusDirect = `-- name: UpdateArticleStatusDirect :one
UPDATE articles SET status = $1, updated_at = now()
WHERE id = $2 AND group_id = $3
RETURNING id, group_id, commercial_name, common_name, category_id, location_id, status, individually_tracked, approval_level, image_ids, description, instructions, manager_notes, purchase_date, purchase_price, place, expected_available_date, import_batch_id, created_at, updated_at
`

type UpdateArticleStatusDirectParams struct {
	Status  string      `json:"status"`
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

// Direct status update used by issue derivation (no expected_available_date reset).
func (q *Queries) UpdateArticleStatusDirect(ctx context.Context, arg UpdateArticleStatusDirectParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticleStatusDirect, arg.Status, arg.ID, arg.GroupID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CommercialName,
		&i.CommonName,
		&i.CategoryID,
		&i.LocationID,
		&i.Status,
		&i.IndividuallyTracked,
		&i.ApprovalLevel,
		&i.ImageIds,
		&i.Description,
		&i.Instructions,
		&i.ManagerNotes,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.Place,
		&i.ExpectedAvailableDate,
		&i.ImportBatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issue_reports SET
    title       = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    status      = COALESCE($3::text, status),
    updated_at  = now()
WHERE id = $4 AND group_id = $5
RETURNING id, group_id, title, description, severity, status, reporter_id, booking_id, created_at, updated_at
`

type UpdateIssueParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	ID          pgtype.UUID `json:"id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (IssueReport, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ID,
		arg.GroupID,
	)
	var i IssueReport
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Status,
		&i.ReporterID,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
