// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (group_id, name, sort_order)
VALUES ($1, $2, $3)
RETURNING id, group_id, name, sort_order, created_at
`

type CreateLocationParams struct {
	GroupID   string `json:"group_id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.GroupID, arg.Name, arg.SortOrder)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations
WHERE id = $1 AND group_id = $2
`

type DeleteLocationParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteLocation(ctx context.Context, arg DeleteLocationParams) error {
	_, err := q.db.Exec(ctx, deleteLocation, arg.ID, arg.GroupID)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, group_id, name, sort_order, created_at FROM locations
WHERE id = $1 AND group_id = $2
`

type GetLocationParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetLocation(ctx context.Context, arg GetLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, arg.ID, arg.GroupID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationByName = `-- name: GetLocationByName :one
SELECT id, group_id, name, sort_order, created_at FROM locations
WHERE group_id = $1 AND name = $2
`

type GetLocationByNameParams struct {
	GroupID string `json:"group_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetLocationByName(ctx context.Context, arg GetLocationByNameParams) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByName, arg.GroupID, arg.Name)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, group_id, name, sort_order, created_at FROM locations
WHERE group_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListLocations(ctx context.Context, groupID string) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations SET name = $1, sort_order = $2
WHERE id = $3 AND group_id = $4
RETURNING id, group_id, name, sort_order, created_at
`

type UpdateLocationParams struct {
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
	GroupID   string      `json:"group_id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.SortOrder,
		arg.ID,
		arg.GroupID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
