// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ApprovalLevel         string             `json:"approval_level"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	ManagerNotes          string             `json:"manager_notes"`
	ImageIds              json.RawMessage    `json:"image_ids"`
}

type ArticleEvent struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	ArticleID   pgtype.UUID        `json:"article_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	Description string             `json:"description"`
	Metadata    json.RawMessage    `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    string             `json:"group_id"`
	UserID     string             `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    json.RawMessage    `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CreatedBy             string             `json:"created_by"`
	UsedByUnitID          pgtype.UUID        `json:"used_by_unit_id"`
	UsedByExternal        pgtype.Text        `json:"used_by_external"`
	UsedByExternalContact pgtype.Text        `json:"used_by_external_contact"`
	Status                string             `json:"status"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PrePickupStatus       pgtype.Text        `json:"pre_pickup_status"`
}

type BookingEvent struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	ActorID   string             `json:"actor_id"`
	EventType string             `json:"event_type"`
	Message   string             `json:"message"`
	Metadata  json.RawMessage    `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BookingItem struct {
	ID           pgtype.UUID `json:"id"`
	GroupID      string      `json:"group_id"`
	BookingID    pgtype.UUID `json:"booking_id"`
	ArticleID    pgtype.UUID `json:"article_id"`
	PickupStatus pgtype.Text `json:"pickup_status"`
	ReturnStatus pgtype.Text `json:"return_status"`
	Notes        string      `json:"notes"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupSetting struct {
	GroupID               string             `json:"group_id"`
	NotificationEmailFrom string             `json:"notification_email_from"`
	SmtpKeyEncrypted      []byte             `json:"smtp_key_encrypted"`
	GchatWebhookUrl       string             `json:"gchat_webhook_url"`
	DefaultApprovalLevel  string             `json:"default_approval_level"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ImageUploadRole       string             `json:"image_upload_role"`
}

type Location struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Package struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Scope       string             `json:"scope"`
	OwnerID     pgtype.Text        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PackageItem struct {
	ID         pgtype.UUID `json:"id"`
	GroupID    string      `json:"group_id"`
	PackageID  pgtype.UUID `json:"package_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	ArticleID  pgtype.UUID `json:"article_id"`
	Quantity   int32       `json:"quantity"`
}

type ProductImage struct {
	ID          pgtype.UUID        `json:"id"`
	FileID      pgtype.UUID        `json:"file_id"`
	GroupID     string             `json:"group_id"`
	UploadedBy  string             `json:"uploaded_by"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Format      string             `json:"format"`
	Shared      bool               `json:"shared"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Attribution string             `json:"attribution"`
	IsReference bool               `json:"is_reference"`
}

type Unit struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         string             `json:"group_id"`
	Name            string             `json:"name"`
	GchatWebhookUrl pgtype.Text        `json:"gchat_webhook_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Type            string             `json:"type"`
}

type User struct {
	ID                  string             `json:"id"`
	GroupID             string             `json:"group_id"`
	Name                string             `json:"name"`
	Email               string             `json:"email"`
	NotificationChannel string             `json:"notification_channel"`
	GchatWebhookUrl     pgtype.Text        `json:"gchat_webhook_url"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
