// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CommercialName        string             `json:"commercial_name"`
	CommonName            string             `json:"common_name"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	LocationID            pgtype.UUID        `json:"location_id"`
	Status                string             `json:"status"`
	IndividuallyTracked   bool               `json:"individually_tracked"`
	ApprovalLevel         string             `json:"approval_level"`
	ImageIds              json.RawMessage    `json:"image_ids"`
	Description           string             `json:"description"`
	Instructions          string             `json:"instructions"`
	ManagerNotes          string             `json:"manager_notes"`
	PurchaseDate          pgtype.Date        `json:"purchase_date"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	Place                 string             `json:"place"`
	ExpectedAvailableDate pgtype.Date        `json:"expected_available_date"`
	ImportBatchID         pgtype.UUID        `json:"import_batch_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ArticleEvent struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	ArticleID   pgtype.UUID        `json:"article_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	Description string             `json:"description"`
	Metadata    json.RawMessage    `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    string             `json:"group_id"`
	UserID     string             `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    json.RawMessage    `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID                    pgtype.UUID        `json:"id"`
	GroupID               string             `json:"group_id"`
	CreatedBy             string             `json:"created_by"`
	UsedByTeamID          pgtype.UUID        `json:"used_by_team_id"`
	UsedByExternal        pgtype.Text        `json:"used_by_external"`
	UsedByExternalContact pgtype.Text        `json:"used_by_external_contact"`
	Status                string             `json:"status"`
	StartDate             pgtype.Date        `json:"start_date"`
	EndDate               pgtype.Date        `json:"end_date"`
	Notes                 string             `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type BookingEvent struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	BookingID pgtype.UUID        `json:"booking_id"`
	ActorID   string             `json:"actor_id"`
	EventType string             `json:"event_type"`
	Message   string             `json:"message"`
	Metadata  json.RawMessage    `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BookingItem struct {
	ID           pgtype.UUID `json:"id"`
	GroupID      string      `json:"group_id"`
	BookingID    pgtype.UUID `json:"booking_id"`
	ArticleID    pgtype.UUID `json:"article_id"`
	PickupStatus pgtype.Text `json:"pickup_status"`
	ReturnStatus pgtype.Text `json:"return_status"`
	Notes        string      `json:"notes"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	Name      string             `json:"name"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupSetting struct {
	GroupID                          string             `json:"group_id"`
	NotificationEmailFrom            string             `json:"notification_email_from"`
	SmtpKeyEncrypted                 []byte             `json:"smtp_key_encrypted"`
	DefaultApprovalLevel             string             `json:"default_approval_level"`
	DefaultAccessUnknown             string             `json:"default_access_unknown"`
	DefaultAccessTroop               string             `json:"default_access_troop"`
	DefaultAccessRole                string             `json:"default_access_role"`
	ImageUploadRole                  string             `json:"image_upload_role"`
	BookingRole                      string             `json:"booking_role"`
	ArticleEditRole                  string             `json:"article_edit_role"`
	IssueResolveRole                 string             `json:"issue_resolve_role"`
	ManagerNotesRole                 string             `json:"manager_notes_role"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
	DefaultLanguage                  string             `json:"default_language"`
	SmtpHost                         string             `json:"smtp_host"`
	SmtpPort                         int32              `json:"smtp_port"`
	SmtpTls                          string             `json:"smtp_tls"`
	SmtpUser                         string             `json:"smtp_user"`
	NotificationDefaults             json.RawMessage    `json:"notification_defaults"`
	LogoFileID                       pgtype.UUID        `json:"logo_file_id"`
	EnabledChannels                  []string           `json:"enabled_channels"`
	GchatServiceAccountJsonEncrypted []byte             `json:"gchat_service_account_json_encrypted"`
	GchatAdminEmail                  string             `json:"gchat_admin_email"`
	DefaultGruppkanalChannels        []string           `json:"default_gruppkanal_channels"`
	SmtpKeyMasked                    string             `json:"smtp_key_masked"`
}

type IssueArticle struct {
	IssueID   pgtype.UUID `json:"issue_id"`
	ArticleID pgtype.UUID `json:"article_id"`
	GroupID   string      `json:"group_id"`
}

type IssueAssignee struct {
	IssueID    pgtype.UUID        `json:"issue_id"`
	UserID     string             `json:"user_id"`
	GroupID    string             `json:"group_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type IssueEvent struct {
	ID          pgtype.UUID        `json:"id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	GroupID     string             `json:"group_id"`
	ActorID     string             `json:"actor_id"`
	EventType   string             `json:"event_type"`
	Description string             `json:"description"`
	Metadata    json.RawMessage    `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IssueReport struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Severity    string             `json:"severity"`
	Status      string             `json:"status"`
	ReporterID  string             `json:"reporter_id"`
	BookingID   pgtype.UUID        `json:"booking_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationLog struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   string             `json:"group_id"`
	UserID    string             `json:"user_id"`
	EventType string             `json:"event_type"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Channel   string             `json:"channel"`
	Status    string             `json:"status"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ThreadKey pgtype.Text        `json:"thread_key"`
	MessageID pgtype.Text        `json:"message_id"`
}

type Package struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Scope       string             `json:"scope"`
	OwnerID     pgtype.Text        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PackageItem struct {
	ID         pgtype.UUID `json:"id"`
	GroupID    string      `json:"group_id"`
	PackageID  pgtype.UUID `json:"package_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	ArticleID  pgtype.UUID `json:"article_id"`
	Quantity   int32       `json:"quantity"`
}

type ProductImage struct {
	ID          pgtype.UUID        `json:"id"`
	FileID      pgtype.UUID        `json:"file_id"`
	GroupID     string             `json:"group_id"`
	UploadedBy  string             `json:"uploaded_by"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Attribution string             `json:"attribution"`
	Format      string             `json:"format"`
	Shared      bool               `json:"shared"`
	IsReference bool               `json:"is_reference"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID                 pgtype.UUID        `json:"id"`
	GroupID            string             `json:"group_id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	AccessLevel        string             `json:"access_level"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	NotificationEmail  pgtype.Text        `json:"notification_email"`
	NotificationPrefs  json.RawMessage    `json:"notification_prefs"`
	GchatSpaceID       pgtype.Text        `json:"gchat_space_id"`
	GruppkanalChannels []string           `json:"gruppkanal_channels"`
}

type TeamClaimMapping struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    string             `json:"group_id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	ClaimScope string             `json:"claim_scope"`
	ClaimID    string             `json:"claim_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                string             `json:"id"`
	GroupID           string             `json:"group_id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	ActiveGroupID     pgtype.Text        `json:"active_group_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Language          pgtype.Text        `json:"language"`
	MaxAccessLevel    string             `json:"max_access_level"`
	NotificationPrefs json.RawMessage    `json:"notification_prefs"`
	TeamIds           []pgtype.UUID      `json:"team_ids"`
	NotificationEmail pgtype.Text        `json:"notification_email"`
}
