// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBroadcastThreadMessageID = `-- name: GetBroadcastThreadMessageID :one
SELECT message_id FROM notification_log
WHERE thread_key = $1
  AND channel = $2
  AND user_id LIKE 'broadcast:%'
  AND message_id IS NOT NULL
ORDER BY created_at ASC
LIMIT 1
`

type GetBroadcastThreadMessageIDParams struct {
	ThreadKey pgtype.Text `json:"thread_key"`
	Channel   string      `json:"channel"`
}

// Returns the stored Message-ID for the first broadcast to a given thread+channel.
func (q *Queries) GetBroadcastThreadMessageID(ctx context.Context, arg GetBroadcastThreadMessageIDParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBroadcastThreadMessageID, arg.ThreadKey, arg.Channel)
	var message_id pgtype.Text
	err := row.Scan(&message_id)
	return message_id, err
}

const getGroupEnabledChannels = `-- name: GetGroupEnabledChannels :one
SELECT enabled_channels FROM group_settings WHERE group_id = $1
`

func (q *Queries) GetGroupEnabledChannels(ctx context.Context, groupID string) ([]string, error) {
	row := q.db.QueryRow(ctx, getGroupEnabledChannels, groupID)
	var enabled_channels []string
	err := row.Scan(&enabled_channels)
	return enabled_channels, err
}

const getThreadMessageID = `-- name: GetThreadMessageID :one
SELECT message_id FROM notification_log
WHERE thread_key = $1
  AND user_id = $2
  AND channel = $3
  AND message_id IS NOT NULL
ORDER BY created_at ASC
LIMIT 1
`

type GetThreadMessageIDParams struct {
	ThreadKey pgtype.Text `json:"thread_key"`
	UserID    string      `json:"user_id"`
	Channel   string      `json:"channel"`
}

// Returns the stored email Message-ID for the first notification in a thread,
// so follow-up sends can set In-Reply-To headers for email threading.
func (q *Queries) GetThreadMessageID(ctx context.Context, arg GetThreadMessageIDParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getThreadMessageID, arg.ThreadKey, arg.UserID, arg.Channel)
	var message_id pgtype.Text
	err := row.Scan(&message_id)
	return message_id, err
}

const hasNotificationBeenSent = `-- name: HasNotificationBeenSent :one
SELECT EXISTS (
    SELECT 1 FROM notification_log
    WHERE entity_id = $1
      AND event_type = $2
      AND user_id = $3
      AND channel = $4
      AND status = 'sent'
) AS sent
`

type HasNotificationBeenSentParams struct {
	EntityID  pgtype.UUID `json:"entity_id"`
	EventType string      `json:"event_type"`
	UserID    string      `json:"user_id"`
	Channel   string      `json:"channel"`
}

func (q *Queries) HasNotificationBeenSent(ctx context.Context, arg HasNotificationBeenSentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasNotificationBeenSent,
		arg.EntityID,
		arg.EventType,
		arg.UserID,
		arg.Channel,
	)
	var sent bool
	err := row.Scan(&sent)
	return sent, err
}

const logNotification = `-- name: LogNotification :exec
INSERT INTO notification_log (group_id, user_id, event_type, entity_id, channel, status, error, thread_key, message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type LogNotificationParams struct {
	GroupID   string      `json:"group_id"`
	UserID    string      `json:"user_id"`
	EventType string      `json:"event_type"`
	EntityID  pgtype.UUID `json:"entity_id"`
	Channel   string      `json:"channel"`
	Status    string      `json:"status"`
	Error     pgtype.Text `json:"error"`
	ThreadKey pgtype.Text `json:"thread_key"`
	MessageID pgtype.Text `json:"message_id"`
}

func (q *Queries) LogNotification(ctx context.Context, arg LogNotificationParams) error {
	_, err := q.db.Exec(ctx, logNotification,
		arg.GroupID,
		arg.UserID,
		arg.EventType,
		arg.EntityID,
		arg.Channel,
		arg.Status,
		arg.Error,
		arg.ThreadKey,
		arg.MessageID,
	)
	return err
}
