// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasNotificationBeenSent = `-- name: HasNotificationBeenSent :one
SELECT EXISTS (
    SELECT 1 FROM notification_log
    WHERE entity_id = $1
      AND event_type = $2
      AND user_id = $3
      AND channel = $4
      AND status = 'sent'
) AS sent
`

type HasNotificationBeenSentParams struct {
	EntityID  pgtype.UUID `json:"entity_id"`
	EventType string      `json:"event_type"`
	UserID    string      `json:"user_id"`
	Channel   string      `json:"channel"`
}

func (q *Queries) HasNotificationBeenSent(ctx context.Context, arg HasNotificationBeenSentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasNotificationBeenSent,
		arg.EntityID,
		arg.EventType,
		arg.UserID,
		arg.Channel,
	)
	var sent bool
	err := row.Scan(&sent)
	return sent, err
}

const logNotification = `-- name: LogNotification :exec
INSERT INTO notification_log (group_id, user_id, event_type, entity_id, channel, status, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type LogNotificationParams struct {
	GroupID   string      `json:"group_id"`
	UserID    string      `json:"user_id"`
	EventType string      `json:"event_type"`
	EntityID  pgtype.UUID `json:"entity_id"`
	Channel   string      `json:"channel"`
	Status    string      `json:"status"`
	Error     pgtype.Text `json:"error"`
}

func (q *Queries) LogNotification(ctx context.Context, arg LogNotificationParams) error {
	_, err := q.db.Exec(ctx, logNotification,
		arg.GroupID,
		arg.UserID,
		arg.EventType,
		arg.EntityID,
		arg.Channel,
		arg.Status,
		arg.Error,
	)
	return err
}
