// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductImagesByFileId = `-- name: CountProductImagesByFileId :one
SELECT COUNT(*) FROM product_images WHERE file_id = $1
`

// Counts how many product_images rows reference the same file on disk.
func (q *Queries) CountProductImagesByFileId(ctx context.Context, fileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductImagesByFileId, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1 AND group_id = $2
`

type DeleteProductImageParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.Exec(ctx, deleteProductImage, arg.ID, arg.GroupID)
	return err
}

const getImageUploadRole = `-- name: GetImageUploadRole :one
SELECT image_upload_role FROM group_settings WHERE group_id = $1
`

func (q *Queries) GetImageUploadRole(ctx context.Context, groupID string) (string, error) {
	row := q.db.QueryRow(ctx, getImageUploadRole, groupID)
	var image_upload_role string
	err := row.Scan(&image_upload_role)
	return image_upload_role, err
}

const getProductImage = `-- name: GetProductImage :one
SELECT pi.id, pi.file_id, pi.group_id, pi.uploaded_by, pi.title, pi.description, pi.format, pi.shared, pi.created_at, pi.attribution, pi.is_reference, u.name AS uploaded_by_name, g.name AS uploaded_by_group
FROM product_images pi
JOIN users u ON pi.uploaded_by = u.id
JOIN groups g ON pi.group_id = g.id
WHERE pi.id = $1
`

type GetProductImageRow struct {
	ID              pgtype.UUID        `json:"id"`
	FileID          pgtype.UUID        `json:"file_id"`
	GroupID         string             `json:"group_id"`
	UploadedBy      string             `json:"uploaded_by"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Format          string             `json:"format"`
	Shared          bool               `json:"shared"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Attribution     string             `json:"attribution"`
	IsReference     bool               `json:"is_reference"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByGroup string             `json:"uploaded_by_group"`
}

func (q *Queries) GetProductImage(ctx context.Context, id pgtype.UUID) (GetProductImageRow, error) {
	row := q.db.QueryRow(ctx, getProductImage, id)
	var i GetProductImageRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.GroupID,
		&i.UploadedBy,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.Shared,
		&i.CreatedAt,
		&i.Attribution,
		&i.IsReference,
		&i.UploadedByName,
		&i.UploadedByGroup,
	)
	return i, err
}

const insertProductImage = `-- name: InsertProductImage :one
INSERT INTO product_images (id, file_id, group_id, uploaded_by, title, description, format, shared, attribution, is_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, file_id, group_id, uploaded_by, title, description, format, shared, created_at, attribution, is_reference
`

type InsertProductImageParams struct {
	ID          pgtype.UUID `json:"id"`
	FileID      pgtype.UUID `json:"file_id"`
	GroupID     string      `json:"group_id"`
	UploadedBy  string      `json:"uploaded_by"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Format      string      `json:"format"`
	Shared      bool        `json:"shared"`
	Attribution string      `json:"attribution"`
	IsReference bool        `json:"is_reference"`
}

func (q *Queries) InsertProductImage(ctx context.Context, arg InsertProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, insertProductImage,
		arg.ID,
		arg.FileID,
		arg.GroupID,
		arg.UploadedBy,
		arg.Title,
		arg.Description,
		arg.Format,
		arg.Shared,
		arg.Attribution,
		arg.IsReference,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.GroupID,
		&i.UploadedBy,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.Shared,
		&i.CreatedAt,
		&i.Attribution,
		&i.IsReference,
	)
	return i, err
}

const listArticlesUsingImage = `-- name: ListArticlesUsingImage :many
SELECT a.id, a.commercial_name, a.common_name, a.individually_tracked,
    l.name AS location_name
FROM articles a
JOIN locations l ON a.location_id = l.id
WHERE a.group_id = $1
    AND a.image_ids @> jsonb_build_array($2::text)
ORDER BY a.commercial_name, a.common_name
`

type ListArticlesUsingImageParams struct {
	GroupID    string `json:"group_id"`
	ImageIDStr string `json:"image_id_str"`
}

type ListArticlesUsingImageRow struct {
	ID                  pgtype.UUID `json:"id"`
	CommercialName      string      `json:"commercial_name"`
	CommonName          string      `json:"common_name"`
	IndividuallyTracked bool        `json:"individually_tracked"`
	LocationName        string      `json:"location_name"`
}

// Returns articles that reference a given image ID in their image_ids array.
func (q *Queries) ListArticlesUsingImage(ctx context.Context, arg ListArticlesUsingImageParams) ([]ListArticlesUsingImageRow, error) {
	rows, err := q.db.Query(ctx, listArticlesUsingImage, arg.GroupID, arg.ImageIDStr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesUsingImageRow{}
	for rows.Next() {
		var i ListArticlesUsingImageRow
		if err := rows.Scan(
			&i.ID,
			&i.CommercialName,
			&i.CommonName,
			&i.IndividuallyTracked,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByIds = `-- name: ListProductImagesByIds :many
SELECT pi.id, pi.file_id, pi.group_id, pi.uploaded_by, pi.title, pi.description, pi.format, pi.shared, pi.created_at, pi.attribution, pi.is_reference, u.name AS uploaded_by_name, g.name AS uploaded_by_group
FROM product_images pi
JOIN users u ON pi.uploaded_by = u.id
JOIN groups g ON pi.group_id = g.id
WHERE pi.file_id = ANY($1::uuid[])
ORDER BY array_position($1::uuid[], pi.file_id)
`

type ListProductImagesByIdsRow struct {
	ID              pgtype.UUID        `json:"id"`
	FileID          pgtype.UUID        `json:"file_id"`
	GroupID         string             `json:"group_id"`
	UploadedBy      string             `json:"uploaded_by"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Format          string             `json:"format"`
	Shared          bool               `json:"shared"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Attribution     string             `json:"attribution"`
	IsReference     bool               `json:"is_reference"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByGroup string             `json:"uploaded_by_group"`
}

// Returns images matching the given file_ids, in order.
func (q *Queries) ListProductImagesByIds(ctx context.Context, ids []pgtype.UUID) ([]ListProductImagesByIdsRow, error) {
	rows, err := q.db.Query(ctx, listProductImagesByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductImagesByIdsRow{}
	for rows.Next() {
		var i ListProductImagesByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.GroupID,
			&i.UploadedBy,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.Shared,
			&i.CreatedAt,
			&i.Attribution,
			&i.IsReference,
			&i.UploadedByName,
			&i.UploadedByGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByUploader = `-- name: ListProductImagesByUploader :many
SELECT pi.id, pi.file_id, pi.group_id, pi.uploaded_by, pi.title, pi.description, pi.format, pi.shared, pi.created_at, pi.attribution, pi.is_reference, u.name AS uploaded_by_name, g.name AS uploaded_by_group,
    (SELECT COUNT(*) FROM product_images p2 WHERE p2.file_id = pi.file_id AND p2.group_id = pi.group_id) AS own_group_count,
    (SELECT COUNT(*) FROM product_images p3 WHERE p3.file_id = pi.file_id AND p3.group_id != pi.group_id) AS other_group_count
FROM product_images pi
JOIN users u ON pi.uploaded_by = u.id
JOIN groups g ON pi.group_id = g.id
WHERE pi.uploaded_by = $1 AND pi.group_id = $2 AND pi.is_reference = false
ORDER BY pi.created_at DESC
`

type ListProductImagesByUploaderParams struct {
	UserID  string `json:"user_id"`
	GroupID string `json:"group_id"`
}

type ListProductImagesByUploaderRow struct {
	ID              pgtype.UUID        `json:"id"`
	FileID          pgtype.UUID        `json:"file_id"`
	GroupID         string             `json:"group_id"`
	UploadedBy      string             `json:"uploaded_by"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Format          string             `json:"format"`
	Shared          bool               `json:"shared"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Attribution     string             `json:"attribution"`
	IsReference     bool               `json:"is_reference"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByGroup string             `json:"uploaded_by_group"`
	OwnGroupCount   int64              `json:"own_group_count"`
	OtherGroupCount int64              `json:"other_group_count"`
}

// Returns original uploads (not references) by a specific user with usage counts.
func (q *Queries) ListProductImagesByUploader(ctx context.Context, arg ListProductImagesByUploaderParams) ([]ListProductImagesByUploaderRow, error) {
	rows, err := q.db.Query(ctx, listProductImagesByUploader, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductImagesByUploaderRow{}
	for rows.Next() {
		var i ListProductImagesByUploaderRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.GroupID,
			&i.UploadedBy,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.Shared,
			&i.CreatedAt,
			&i.Attribution,
			&i.IsReference,
			&i.UploadedByName,
			&i.UploadedByGroup,
			&i.OwnGroupCount,
			&i.OtherGroupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedImages = `-- name: ListSharedImages :many
SELECT pi.id, pi.file_id, pi.group_id, pi.uploaded_by, pi.title, pi.description, pi.format, pi.shared, pi.created_at, pi.attribution, pi.is_reference, u.name AS uploaded_by_name, g.name AS uploaded_by_group
FROM product_images pi
JOIN users u ON pi.uploaded_by = u.id
JOIN groups g ON pi.group_id = g.id
WHERE pi.is_reference = false
    AND (pi.shared = true OR pi.group_id = $1)
    AND ($2::text IS NULL
        OR pi.title ILIKE '%' || $2 || '%'
        OR pi.description ILIKE '%' || $2 || '%')
ORDER BY pi.created_at DESC
`

type ListSharedImagesParams struct {
	GroupID string      `json:"group_id"`
	Search  pgtype.Text `json:"search"`
}

type ListSharedImagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	FileID          pgtype.UUID        `json:"file_id"`
	GroupID         string             `json:"group_id"`
	UploadedBy      string             `json:"uploaded_by"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Format          string             `json:"format"`
	Shared          bool               `json:"shared"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Attribution     string             `json:"attribution"`
	IsReference     bool               `json:"is_reference"`
	UploadedByName  string             `json:"uploaded_by_name"`
	UploadedByGroup string             `json:"uploaded_by_group"`
}

// Returns original uploads (not references) that are shared or from the current group.
func (q *Queries) ListSharedImages(ctx context.Context, arg ListSharedImagesParams) ([]ListSharedImagesRow, error) {
	rows, err := q.db.Query(ctx, listSharedImages, arg.GroupID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedImagesRow{}
	for rows.Next() {
		var i ListSharedImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.GroupID,
			&i.UploadedBy,
			&i.Title,
			&i.Description,
			&i.Format,
			&i.Shared,
			&i.CreatedAt,
			&i.Attribution,
			&i.IsReference,
			&i.UploadedByName,
			&i.UploadedByGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeImageIdFromAllArticles = `-- name: RemoveImageIdFromAllArticles :execrows
UPDATE articles
SET image_ids = image_ids - $1, updated_at = now()
WHERE group_id = $2
    AND image_ids @> jsonb_build_array($1)
`

type RemoveImageIdFromAllArticlesParams struct {
	ImageIDStr json.RawMessage `json:"image_id_str"`
	GroupID    string          `json:"group_id"`
}

// Removes a specific image ID from the image_ids array on all articles in a group.
func (q *Queries) RemoveImageIdFromAllArticles(ctx context.Context, arg RemoveImageIdFromAllArticlesParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeImageIdFromAllArticles, arg.ImageIDStr, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE product_images
SET title = $1, description = $2, shared = $3, attribution = $4
WHERE id = $5 AND group_id = $6
RETURNING id, file_id, group_id, uploaded_by, title, description, format, shared, created_at, attribution, is_reference
`

type UpdateProductImageParams struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Shared      bool        `json:"shared"`
	Attribution string      `json:"attribution"`
	ID          pgtype.UUID `json:"id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, updateProductImage,
		arg.Title,
		arg.Description,
		arg.Shared,
		arg.Attribution,
		arg.ID,
		arg.GroupID,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.GroupID,
		&i.UploadedBy,
		&i.Title,
		&i.Description,
		&i.Format,
		&i.Shared,
		&i.CreatedAt,
		&i.Attribution,
		&i.IsReference,
	)
	return i, err
}
