// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_claim_mappings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamClaimMapping = `-- name: CreateTeamClaimMapping :one
INSERT INTO team_claim_mappings (group_id, team_id, claim_scope, claim_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (group_id, claim_scope, claim_id) DO NOTHING
RETURNING id, group_id, team_id, claim_scope, claim_id, created_at
`

type CreateTeamClaimMappingParams struct {
	GroupID    string      `json:"group_id"`
	TeamID     pgtype.UUID `json:"team_id"`
	ClaimScope string      `json:"claim_scope"`
	ClaimID    string      `json:"claim_id"`
}

func (q *Queries) CreateTeamClaimMapping(ctx context.Context, arg CreateTeamClaimMappingParams) (TeamClaimMapping, error) {
	row := q.db.QueryRow(ctx, createTeamClaimMapping,
		arg.GroupID,
		arg.TeamID,
		arg.ClaimScope,
		arg.ClaimID,
	)
	var i TeamClaimMapping
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TeamID,
		&i.ClaimScope,
		&i.ClaimID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeamClaimMapping = `-- name: DeleteTeamClaimMapping :exec
DELETE FROM team_claim_mappings
WHERE id = $1 AND group_id = $2
`

type DeleteTeamClaimMappingParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteTeamClaimMapping(ctx context.Context, arg DeleteTeamClaimMappingParams) error {
	_, err := q.db.Exec(ctx, deleteTeamClaimMapping, arg.ID, arg.GroupID)
	return err
}

const getTeamClaimMappingsByClaims = `-- name: GetTeamClaimMappingsByClaims :many
SELECT tcm.claim_scope, tcm.claim_id, t.id AS team_id, t.name AS team_name, t.type AS team_type, t.access_level
FROM team_claim_mappings tcm
JOIN teams t ON t.id = tcm.team_id
WHERE tcm.group_id = $1
`

type GetTeamClaimMappingsByClaimsRow struct {
	ClaimScope  string      `json:"claim_scope"`
	ClaimID     string      `json:"claim_id"`
	TeamID      pgtype.UUID `json:"team_id"`
	TeamName    string      `json:"team_name"`
	TeamType    string      `json:"team_type"`
	AccessLevel string      `json:"access_level"`
}

func (q *Queries) GetTeamClaimMappingsByClaims(ctx context.Context, groupID string) ([]GetTeamClaimMappingsByClaimsRow, error) {
	rows, err := q.db.Query(ctx, getTeamClaimMappingsByClaims, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamClaimMappingsByClaimsRow{}
	for rows.Next() {
		var i GetTeamClaimMappingsByClaimsRow
		if err := rows.Scan(
			&i.ClaimScope,
			&i.ClaimID,
			&i.TeamID,
			&i.TeamName,
			&i.TeamType,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamClaimMappings = `-- name: ListTeamClaimMappings :many
SELECT tcm.id, tcm.group_id, tcm.team_id, tcm.claim_scope, tcm.claim_id, tcm.created_at, t.name AS team_name, t.type AS team_type, t.access_level
FROM team_claim_mappings tcm
JOIN teams t ON t.id = tcm.team_id
WHERE tcm.group_id = $1
ORDER BY t.name
`

type ListTeamClaimMappingsRow struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     string             `json:"group_id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	ClaimScope  string             `json:"claim_scope"`
	ClaimID     string             `json:"claim_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TeamName    string             `json:"team_name"`
	TeamType    string             `json:"team_type"`
	AccessLevel string             `json:"access_level"`
}

func (q *Queries) ListTeamClaimMappings(ctx context.Context, groupID string) ([]ListTeamClaimMappingsRow, error) {
	rows, err := q.db.Query(ctx, listTeamClaimMappings, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamClaimMappingsRow{}
	for rows.Next() {
		var i ListTeamClaimMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TeamID,
			&i.ClaimScope,
			&i.ClaimID,
			&i.CreatedAt,
			&i.TeamName,
			&i.TeamType,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
