// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBookingsForTeam = `-- name: CountActiveBookingsForTeam :one
SELECT count(*) FROM bookings
WHERE used_by_team_id = $1 AND group_id = $2
AND status NOT IN ('returned', 'cancelled')
`

type CountActiveBookingsForTeamParams struct {
	TeamID  pgtype.UUID `json:"team_id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) CountActiveBookingsForTeam(ctx context.Context, arg CountActiveBookingsForTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBookingsForTeam, arg.TeamID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (group_id, name, type, access_level)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, name, type, access_level, gchat_webhook_url, created_at
`

type CreateTeamParams struct {
	GroupID     string `json:"group_id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	AccessLevel string `json:"access_level"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.GroupID,
		arg.Name,
		arg.Type,
		arg.AccessLevel,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1 AND group_id = $2
`

type DeleteTeamParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.GroupID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, group_id, name, type, access_level, gchat_webhook_url, created_at FROM teams
WHERE id = $1 AND group_id = $2
`

type GetTeamParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.GroupID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, group_id, name, type, access_level, gchat_webhook_url, created_at FROM teams
WHERE group_id = $1 AND name = $2
LIMIT 1
`

type GetTeamByNameParams struct {
	GroupID string `json:"group_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.GroupID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.group_id, t.name, t.type, t.access_level, t.gchat_webhook_url, t.created_at,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('claim_scope', tcm.claim_scope, 'claim_id', tcm.claim_id))
         FROM team_claim_mappings tcm WHERE tcm.team_id = t.id),
        '[]'::jsonb
    ) AS claim_mappings
FROM teams t
WHERE t.group_id = $1
ORDER BY t.name
`

type ListTeamsRow struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         string             `json:"group_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	AccessLevel     string             `json:"access_level"`
	GchatWebhookUrl pgtype.Text        `json:"gchat_webhook_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ClaimMappings   interface{}        `json:"claim_mappings"`
}

func (q *Queries) ListTeams(ctx context.Context, groupID string) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Type,
			&i.AccessLevel,
			&i.GchatWebhookUrl,
			&i.CreatedAt,
			&i.ClaimMappings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByNames = `-- name: ListTeamsByNames :many
SELECT id, group_id, name, type, access_level, gchat_webhook_url, created_at FROM teams
WHERE group_id = $1 AND name = ANY($2::text[])
`

type ListTeamsByNamesParams struct {
	GroupID string   `json:"group_id"`
	Names   []string `json:"names"`
}

func (q *Queries) ListTeamsByNames(ctx context.Context, arg ListTeamsByNamesParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByNames, arg.GroupID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Type,
			&i.AccessLevel,
			&i.GchatWebhookUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET
    name = $1,
    type = $2,
    access_level = $3
WHERE id = $4 AND group_id = $5
RETURNING id, group_id, name, type, access_level, gchat_webhook_url, created_at
`

type UpdateTeamParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	AccessLevel string      `json:"access_level"`
	ID          pgtype.UUID `json:"id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.Type,
		arg.AccessLevel,
		arg.ID,
		arg.GroupID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
	)
	return i, err
}
