// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearTeamGchatSpace = `-- name: ClearTeamGchatSpace :exec
UPDATE teams SET gchat_space_id = NULL
WHERE id = $1 AND group_id = $2
`

type ClearTeamGchatSpaceParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) ClearTeamGchatSpace(ctx context.Context, arg ClearTeamGchatSpaceParams) error {
	_, err := q.db.Exec(ctx, clearTeamGchatSpace, arg.ID, arg.GroupID)
	return err
}

const countActiveBookingsForTeam = `-- name: CountActiveBookingsForTeam :one
SELECT count(*) FROM bookings
WHERE used_by_team_id = $1 AND group_id = $2
AND status NOT IN ('returned', 'cancelled')
`

type CountActiveBookingsForTeamParams struct {
	TeamID  pgtype.UUID `json:"team_id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) CountActiveBookingsForTeam(ctx context.Context, arg CountActiveBookingsForTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBookingsForTeam, arg.TeamID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countManagerTeams = `-- name: CountManagerTeams :one
SELECT count(*) FROM teams
WHERE group_id = $1 AND access_level = 'manager'
`

func (q *Queries) CountManagerTeams(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countManagerTeams, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (group_id, name, type, access_level)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id
`

type CreateTeamParams struct {
	GroupID     string `json:"group_id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	AccessLevel string `json:"access_level"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.GroupID,
		arg.Name,
		arg.Type,
		arg.AccessLevel,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1 AND group_id = $2
`

type DeleteTeamParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) DeleteTeam(ctx context.Context, arg DeleteTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTeam, arg.ID, arg.GroupID)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id FROM teams
WHERE id = $1 AND group_id = $2
`

type GetTeamParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID, arg.GroupID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id FROM teams
WHERE group_id = $1 AND name = $2
LIMIT 1
`

type GetTeamByNameParams struct {
	GroupID string `json:"group_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, arg.GroupID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const getTeamNotificationSettings = `-- name: GetTeamNotificationSettings :one
SELECT notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id
FROM teams
WHERE id = $1 AND group_id = $2
`

type GetTeamNotificationSettingsParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

type GetTeamNotificationSettingsRow struct {
	NotificationEmail              pgtype.Text     `json:"notification_email"`
	NotificationPrefs              json.RawMessage `json:"notification_prefs"`
	IndividualNotificationsEnabled bool            `json:"individual_notifications_enabled"`
	GchatSpaceID                   pgtype.Text     `json:"gchat_space_id"`
}

func (q *Queries) GetTeamNotificationSettings(ctx context.Context, arg GetTeamNotificationSettingsParams) (GetTeamNotificationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getTeamNotificationSettings, arg.ID, arg.GroupID)
	var i GetTeamNotificationSettingsRow
	err := row.Scan(
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE id = $1 AND group_id = $2 AND $3::uuid = ANY(team_ids)
) AS is_member
`

type IsTeamMemberParams struct {
	UserID  string      `json:"user_id"`
	GroupID string      `json:"group_id"`
	TeamID  pgtype.UUID `json:"team_id"`
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamMember, arg.UserID, arg.GroupID, arg.TeamID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.group_id, t.name, t.type, t.access_level, t.created_at, t.notification_email, t.notification_prefs, t.individual_notifications_enabled, t.gchat_space_id,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('claim_scope', tcm.claim_scope, 'claim_id', tcm.claim_id))
         FROM team_claim_mappings tcm WHERE tcm.team_id = t.id),
        '[]'::jsonb
    ) AS claim_mappings
FROM teams t
WHERE t.group_id = $1
ORDER BY t.name
`

type ListTeamsRow struct {
	ID                             pgtype.UUID        `json:"id"`
	GroupID                        string             `json:"group_id"`
	Name                           string             `json:"name"`
	Type                           string             `json:"type"`
	AccessLevel                    string             `json:"access_level"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	NotificationEmail              pgtype.Text        `json:"notification_email"`
	NotificationPrefs              json.RawMessage    `json:"notification_prefs"`
	IndividualNotificationsEnabled bool               `json:"individual_notifications_enabled"`
	GchatSpaceID                   pgtype.Text        `json:"gchat_space_id"`
	ClaimMappings                  interface{}        `json:"claim_mappings"`
}

func (q *Queries) ListTeams(ctx context.Context, groupID string) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Type,
			&i.AccessLevel,
			&i.CreatedAt,
			&i.NotificationEmail,
			&i.NotificationPrefs,
			&i.IndividualNotificationsEnabled,
			&i.GchatSpaceID,
			&i.ClaimMappings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByNames = `-- name: ListTeamsByNames :many
SELECT id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id FROM teams
WHERE group_id = $1 AND name = ANY($2::text[])
`

type ListTeamsByNamesParams struct {
	GroupID string   `json:"group_id"`
	Names   []string `json:"names"`
}

func (q *Queries) ListTeamsByNames(ctx context.Context, arg ListTeamsByNamesParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByNames, arg.GroupID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Type,
			&i.AccessLevel,
			&i.CreatedAt,
			&i.NotificationEmail,
			&i.NotificationPrefs,
			&i.IndividualNotificationsEnabled,
			&i.GchatSpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsWithGchatInfo = `-- name: ListTeamsWithGchatInfo :many
SELECT id, name, gchat_space_id FROM teams
WHERE group_id = $1
ORDER BY name
`

type ListTeamsWithGchatInfoRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	GchatSpaceID pgtype.Text `json:"gchat_space_id"`
}

func (q *Queries) ListTeamsWithGchatInfo(ctx context.Context, groupID string) ([]ListTeamsWithGchatInfoRow, error) {
	rows, err := q.db.Query(ctx, listTeamsWithGchatInfo, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsWithGchatInfoRow{}
	for rows.Next() {
		var i ListTeamsWithGchatInfoRow
		if err := rows.Scan(&i.ID, &i.Name, &i.GchatSpaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamGchatSpace = `-- name: SetTeamGchatSpace :exec
UPDATE teams SET gchat_space_id = $1
WHERE id = $2 AND group_id = $3
`

type SetTeamGchatSpaceParams struct {
	GchatSpaceID pgtype.Text `json:"gchat_space_id"`
	ID           pgtype.UUID `json:"id"`
	GroupID      string      `json:"group_id"`
}

func (q *Queries) SetTeamGchatSpace(ctx context.Context, arg SetTeamGchatSpaceParams) error {
	_, err := q.db.Exec(ctx, setTeamGchatSpace, arg.GchatSpaceID, arg.ID, arg.GroupID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET
    name = $1,
    type = $2,
    access_level = $3
WHERE id = $4 AND group_id = $5
RETURNING id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id
`

type UpdateTeamParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	AccessLevel string      `json:"access_level"`
	ID          pgtype.UUID `json:"id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.Type,
		arg.AccessLevel,
		arg.ID,
		arg.GroupID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams SET name = $1
WHERE id = $2 AND group_id = $3
RETURNING id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id
`

type UpdateTeamNameParams struct {
	Name    string      `json:"name"`
	ID      pgtype.UUID `json:"id"`
	GroupID string      `json:"group_id"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.Name, arg.ID, arg.GroupID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}

const updateTeamNotificationSettings = `-- name: UpdateTeamNotificationSettings :one
UPDATE teams SET
    notification_email = $1,
    notification_prefs = $2,
    individual_notifications_enabled = $3
WHERE id = $4 AND group_id = $5
RETURNING id, group_id, name, type, access_level, created_at, notification_email, notification_prefs, individual_notifications_enabled, gchat_space_id
`

type UpdateTeamNotificationSettingsParams struct {
	NotificationEmail              pgtype.Text     `json:"notification_email"`
	NotificationPrefs              json.RawMessage `json:"notification_prefs"`
	IndividualNotificationsEnabled bool            `json:"individual_notifications_enabled"`
	ID                             pgtype.UUID     `json:"id"`
	GroupID                        string          `json:"group_id"`
}

func (q *Queries) UpdateTeamNotificationSettings(ctx context.Context, arg UpdateTeamNotificationSettingsParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamNotificationSettings,
		arg.NotificationEmail,
		arg.NotificationPrefs,
		arg.IndividualNotificationsEnabled,
		arg.ID,
		arg.GroupID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Type,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.NotificationEmail,
		&i.NotificationPrefs,
		&i.IndividualNotificationsEnabled,
		&i.GchatSpaceID,
	)
	return i, err
}
