// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (group_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, group_id, name, gchat_webhook_url, created_at, type
`

type CreateUnitParams struct {
	GroupID string `json:"group_id"`
	Name    string `json:"name"`
	Type    string `json:"type"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit, arg.GroupID, arg.Name, arg.Type)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.GchatWebhookUrl,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}
