// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, group_id, name, email, notification_channel, gchat_webhook_url, active_group_id, created_at, updated_at, language FROM users
WHERE id = $1 AND group_id = $2
`

type GetUserParams struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.GroupID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Email,
		&i.NotificationChannel,
		&i.GchatWebhookUrl,
		&i.ActiveGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}

const updateUserLanguage = `-- name: UpdateUserLanguage :exec
UPDATE users SET language = $1, updated_at = now()
WHERE id = $2 AND group_id = $3
`

type UpdateUserLanguageParams struct {
	Language pgtype.Text `json:"language"`
	ID       string      `json:"id"`
	GroupID  string      `json:"group_id"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) error {
	_, err := q.db.Exec(ctx, updateUserLanguage, arg.Language, arg.ID, arg.GroupID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, group_id, name, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    updated_at = now()
RETURNING id, group_id, name, email, notification_channel, gchat_webhook_url, active_group_id, created_at, updated_at, language
`

type UpsertUserParams struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
	Name    string `json:"name"`
	Email   string `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Email,
		&i.NotificationChannel,
		&i.GchatWebhookUrl,
		&i.ActiveGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}
